;!knitout-2
;;Carriers: 1 2 3 4 5 6 7 8 9 10
;begin alternating tuck cast-on
inhook 1
tuck - f34 1
tuck - f32 1
miss - f31 1
tuck + f31 1
tuck + f33 1
tuck + f35 1
tuck - f34 1
tuck - f32 1
miss - f31 1
knit - f30 1
knit - f28 1
knit - f26 1
knit - f24 1
knit - f22 1
knit - f20 1
knit - f18 1
knit - f16 1
knit - f14 1
knit - f12 1
knit - f10 1
knit - f8 1
knit - f6 1
knit - f4 1
knit - f2 1
knit - f0 1
miss + f0 1
knit + f1 1
knit + f3 1
knit + f5 1
knit + f7 1
knit + f9 1
knit + f11 1
knit + f13 1
knit + f15 1
knit + f17 1
knit + f19 1
knit + f21 1
knit + f23 1
knit + f25 1
knit + f27 1
knit + f29 1
releasehook 1
drop f31
drop f32
drop f33
drop f34
drop f35
;end alternating tuck cast-on
;begin jersey
knit - f30 1
knit - f29 1
knit - f28 1
knit - f27 1
knit - f26 1
knit - f25 1
knit - f24 1
knit - f23 1
knit - f22 1
knit - f21 1
knit - f20 1
knit - f19 1
knit - f18 1
knit - f17 1
knit - f16 1
knit - f15 1
knit - f14 1
knit - f13 1
knit - f12 1
knit - f11 1
knit - f10 1
knit - f9 1
knit - f8 1
knit - f7 1
knit - f6 1
knit - f5 1
knit - f4 1
knit - f3 1
knit - f2 1
knit - f1 1
knit - f0 1
knit + f0 1
knit + f1 1
knit + f2 1
knit + f3 1
knit + f4 1
knit + f5 1
knit + f6 1
knit + f7 1
knit + f8 1
knit + f9 1
knit + f10 1
knit + f11 1
knit + f12 1
knit + f13 1
knit + f14 1
knit + f15 1
knit + f16 1
knit + f17 1
knit + f18 1
knit + f19 1
knit + f20 1
knit + f21 1
knit + f22 1
knit + f23 1
knit + f24 1
knit + f25 1
knit + f26 1
knit + f27 1
knit + f28 1
knit + f29 1
knit + f30 1
knit - f30 1
knit - f29 1
knit - f28 1
knit - f27 1
knit - f26 1
knit - f25 1
knit - f24 1
knit - f23 1
knit - f22 1
knit - f21 1
knit - f20 1
knit - f19 1
knit - f18 1
knit - f17 1
knit - f16 1
knit - f15 1
knit - f14 1
knit - f13 1
knit - f12 1
knit - f11 1
knit - f10 1
knit - f9 1
knit - f8 1
knit - f7 1
knit - f6 1
knit - f5 1
knit - f4 1
knit - f3 1
knit - f2 1
knit - f1 1
knit - f0 1
knit + f0 1
knit + f1 1
knit + f2 1
knit + f3 1
knit + f4 1
knit + f5 1
knit + f6 1
knit + f7 1
knit + f8 1
knit + f9 1
knit + f10 1
knit + f11 1
knit + f12 1
knit + f13 1
knit + f14 1
knit + f15 1
knit + f16 1
knit + f17 1
knit + f18 1
knit + f19 1
knit + f20 1
knit + f21 1
knit + f22 1
knit + f23 1
knit + f24 1
knit + f25 1
knit + f26 1
knit + f27 1
knit + f28 1
knit + f29 1
knit + f30 1
knit - f30 1
knit - f29 1
knit - f28 1
knit - f27 1
knit - f26 1
knit - f25 1
knit - f24 1
knit - f23 1
knit - f22 1
knit - f21 1
knit - f20 1
knit - f19 1
knit - f18 1
knit - f17 1
knit - f16 1
knit - f15 1
knit - f14 1
knit - f13 1
knit - f12 1
knit - f11 1
knit - f10 1
knit - f9 1
knit - f8 1
knit - f7 1
knit - f6 1
knit - f5 1
knit - f4 1
knit - f3 1
knit - f2 1
knit - f1 1
knit - f0 1
knit + f0 1
knit + f1 1
knit + f2 1
knit + f3 1
knit + f4 1
knit + f5 1
knit + f6 1
knit + f7 1
knit + f8 1
knit + f9 1
knit + f10 1
knit + f11 1
knit + f12 1
knit + f13 1
knit + f14 1
knit + f15 1
knit + f16 1
knit + f17 1
knit + f18 1
knit + f19 1
knit + f20 1
knit + f21 1
knit + f22 1
knit + f23 1
knit + f24 1
knit + f25 1
knit + f26 1
knit + f27 1
knit + f28 1
knit + f29 1
knit + f30 1
knit - f30 1
knit - f29 1
knit - f28 1
knit - f27 1
knit - f26 1
knit - f25 1
knit - f24 1
knit - f23 1
knit - f22 1
knit - f21 1
knit - f20 1
knit - f19 1
knit - f18 1
knit - f17 1
knit - f16 1
knit - f15 1
knit - f14 1
knit - f13 1
knit - f12 1
knit - f11 1
knit - f10 1
knit - f9 1
knit - f8 1
knit - f7 1
knit - f6 1
knit - f5 1
knit - f4 1
knit - f3 1
knit - f2 1
knit - f1 1
knit - f0 1
knit + f0 1
knit + f1 1
knit + f2 1
knit + f3 1
knit + f4 1
knit + f5 1
knit + f6 1
knit + f7 1
knit + f8 1
knit + f9 1
knit + f10 1
knit + f11 1
knit + f12 1
knit + f13 1
knit + f14 1
knit + f15 1
knit + f16 1
knit + f17 1
knit + f18 1
knit + f19 1
knit + f20 1
knit + f21 1
knit + f22 1
knit + f23 1
knit + f24 1
knit + f25 1
knit + f26 1
knit + f27 1
knit + f28 1
knit + f29 1
knit + f30 1
knit - f30 1
knit - f29 1
knit - f28 1
knit - f27 1
knit - f26 1
knit - f25 1
knit - f24 1
knit - f23 1
knit - f22 1
knit - f21 1
knit - f20 1
knit - f19 1
knit - f18 1
knit - f17 1
knit - f16 1
knit - f15 1
knit - f14 1
knit - f13 1
knit - f12 1
knit - f11 1
knit - f10 1
knit - f9 1
knit - f8 1
knit - f7 1
knit - f6 1
knit - f5 1
knit - f4 1
knit - f3 1
knit - f2 1
knit - f1 1
knit - f0 1
knit + f0 1
knit + f1 1
knit + f2 1
knit + f3 1
knit + f4 1
knit + f5 1
knit + f6 1
knit + f7 1
knit + f8 1
knit + f9 1
knit + f10 1
knit + f11 1
knit + f12 1
knit + f13 1
knit + f14 1
knit + f15 1
knit + f16 1
knit + f17 1
knit + f18 1
knit + f19 1
knit + f20 1
knit + f21 1
knit + f22 1
knit + f23 1
knit + f24 1
knit + f25 1
knit + f26 1
knit + f27 1
knit + f28 1
knit + f29 1
knit + f30 1
knit - f30 1
knit - f29 1
knit - f28 1
knit - f27 1
knit - f26 1
knit - f25 1
knit - f24 1
knit - f23 1
knit - f22 1
knit - f21 1
knit - f20 1
knit - f19 1
knit - f18 1
knit - f17 1
knit - f16 1
knit - f15 1
knit - f14 1
knit - f13 1
knit - f12 1
knit - f11 1
knit - f10 1
knit - f9 1
knit - f8 1
knit - f7 1
knit - f6 1
knit - f5 1
knit - f4 1
knit - f3 1
knit - f2 1
knit - f1 1
knit - f0 1
knit + f0 1
knit + f1 1
knit + f2 1
knit + f3 1
knit + f4 1
knit + f5 1
knit + f6 1
knit + f7 1
knit + f8 1
knit + f9 1
knit + f10 1
knit + f11 1
knit + f12 1
knit + f13 1
knit + f14 1
knit + f15 1
knit + f16 1
knit + f17 1
knit + f18 1
knit + f19 1
knit + f20 1
knit + f21 1
knit + f22 1
knit + f23 1
knit + f24 1
knit + f25 1
knit + f26 1
knit + f27 1
knit + f28 1
knit + f29 1
knit + f30 1
knit - f30 1
knit - f29 1
knit - f28 1
knit - f27 1
knit - f26 1
knit - f25 1
knit - f24 1
knit - f23 1
knit - f22 1
knit - f21 1
knit - f20 1
knit - f19 1
knit - f18 1
knit - f17 1
knit - f16 1
knit - f15 1
knit - f14 1
knit - f13 1
knit - f12 1
knit - f11 1
knit - f10 1
knit - f9 1
knit - f8 1
knit - f7 1
knit - f6 1
knit - f5 1
knit - f4 1
knit - f3 1
knit - f2 1
knit - f1 1
knit - f0 1
knit + f0 1
knit + f1 1
knit + f2 1
knit + f3 1
knit + f4 1
knit + f5 1
knit + f6 1
knit + f7 1
knit + f8 1
knit + f9 1
knit + f10 1
knit + f11 1
knit + f12 1
knit + f13 1
knit + f14 1
knit + f15 1
knit + f16 1
knit + f17 1
knit + f18 1
knit + f19 1
knit + f20 1
knit + f21 1
knit + f22 1
knit + f23 1
knit + f24 1
knit + f25 1
knit + f26 1
knit + f27 1
knit + f28 1
knit + f29 1
knit + f30 1
knit - f30 1
knit - f29 1
knit - f28 1
knit - f27 1
knit - f26 1
knit - f25 1
knit - f24 1
knit - f23 1
knit - f22 1
knit - f21 1
knit - f20 1
knit - f19 1
knit - f18 1
knit - f17 1
knit - f16 1
knit - f15 1
knit - f14 1
knit - f13 1
knit - f12 1
knit - f11 1
knit - f10 1
knit - f9 1
knit - f8 1
knit - f7 1
knit - f6 1
knit - f5 1
knit - f4 1
knit - f3 1
knit - f2 1
knit - f1 1
knit - f0 1
knit + f0 1
knit + f1 1
knit + f2 1
knit + f3 1
knit + f4 1
knit + f5 1
knit + f6 1
knit + f7 1
knit + f8 1
knit + f9 1
knit + f10 1
knit + f11 1
knit + f12 1
knit + f13 1
knit + f14 1
knit + f15 1
knit + f16 1
knit + f17 1
knit + f18 1
knit + f19 1
knit + f20 1
knit + f21 1
knit + f22 1
knit + f23 1
knit + f24 1
knit + f25 1
knit + f26 1
knit + f27 1
knit + f28 1
knit + f29 1
knit + f30 1
knit - f30 1
knit - f29 1
knit - f28 1
knit - f27 1
knit - f26 1
knit - f25 1
knit - f24 1
knit - f23 1
knit - f22 1
knit - f21 1
knit - f20 1
knit - f19 1
knit - f18 1
knit - f17 1
knit - f16 1
knit - f15 1
knit - f14 1
knit - f13 1
knit - f12 1
knit - f11 1
knit - f10 1
knit - f9 1
knit - f8 1
knit - f7 1
knit - f6 1
knit - f5 1
knit - f4 1
knit - f3 1
knit - f2 1
knit - f1 1
knit - f0 1
knit + f0 1
knit + f1 1
knit + f2 1
knit + f3 1
knit + f4 1
knit + f5 1
knit + f6 1
knit + f7 1
knit + f8 1
knit + f9 1
knit + f10 1
knit + f11 1
knit + f12 1
knit + f13 1
knit + f14 1
knit + f15 1
knit + f16 1
knit + f17 1
knit + f18 1
knit + f19 1
knit + f20 1
knit + f21 1
knit + f22 1
knit + f23 1
knit + f24 1
knit + f25 1
knit + f26 1
knit + f27 1
knit + f28 1
knit + f29 1
knit + f30 1
knit - f30 1
knit - f29 1
knit - f28 1
knit - f27 1
knit - f26 1
knit - f25 1
knit - f24 1
knit - f23 1
knit - f22 1
knit - f21 1
knit - f20 1
knit - f19 1
knit - f18 1
knit - f17 1
knit - f16 1
knit - f15 1
knit - f14 1
knit - f13 1
knit - f12 1
knit - f11 1
knit - f10 1
knit - f9 1
knit - f8 1
knit - f7 1
knit - f6 1
knit - f5 1
knit - f4 1
knit - f3 1
knit - f2 1
knit - f1 1
knit - f0 1
knit + f0 1
knit + f1 1
knit + f2 1
knit + f3 1
knit + f4 1
knit + f5 1
knit + f6 1
knit + f7 1
knit + f8 1
knit + f9 1
knit + f10 1
knit + f11 1
knit + f12 1
knit + f13 1
knit + f14 1
knit + f15 1
knit + f16 1
knit + f17 1
knit + f18 1
knit + f19 1
knit + f20 1
knit + f21 1
knit + f22 1
knit + f23 1
knit + f24 1
knit + f25 1
knit + f26 1
knit + f27 1
knit + f28 1
knit + f29 1
knit + f30 1
knit - f30 1
knit - f29 1
knit - f28 1
knit - f27 1
knit - f26 1
knit - f25 1
knit - f24 1
knit - f23 1
knit - f22 1
knit - f21 1
knit - f20 1
knit - f19 1
knit - f18 1
knit - f17 1
knit - f16 1
knit - f15 1
knit - f14 1
knit - f13 1
knit - f12 1
knit - f11 1
knit - f10 1
knit - f9 1
knit - f8 1
knit - f7 1
knit - f6 1
knit - f5 1
knit - f4 1
knit - f3 1
knit - f2 1
knit - f1 1
knit - f0 1
knit + f0 1
knit + f1 1
knit + f2 1
knit + f3 1
knit + f4 1
knit + f5 1
knit + f6 1
knit + f7 1
knit + f8 1
knit + f9 1
knit + f10 1
knit + f11 1
knit + f12 1
knit + f13 1
knit + f14 1
knit + f15 1
knit + f16 1
knit + f17 1
knit + f18 1
knit + f19 1
knit + f20 1
knit + f21 1
knit + f22 1
knit + f23 1
knit + f24 1
knit + f25 1
knit + f26 1
knit + f27 1
knit + f28 1
knit + f29 1
knit + f30 1
knit - f30 1
knit - f29 1
knit - f28 1
knit - f27 1
knit - f26 1
knit - f25 1
knit - f24 1
knit - f23 1
knit - f22 1
knit - f21 1
knit - f20 1
knit - f19 1
knit - f18 1
knit - f17 1
knit - f16 1
knit - f15 1
knit - f14 1
knit - f13 1
knit - f12 1
knit - f11 1
knit - f10 1
knit - f9 1
knit - f8 1
knit - f7 1
knit - f6 1
knit - f5 1
knit - f4 1
knit - f3 1
knit - f2 1
knit - f1 1
knit - f0 1
knit + f0 1
knit + f1 1
knit + f2 1
knit + f3 1
knit + f4 1
knit + f5 1
knit + f6 1
knit + f7 1
knit + f8 1
knit + f9 1
knit + f10 1
knit + f11 1
knit + f12 1
knit + f13 1
knit + f14 1
knit + f15 1
knit + f16 1
knit + f17 1
knit + f18 1
knit + f19 1
knit + f20 1
knit + f21 1
knit + f22 1
knit + f23 1
knit + f24 1
knit + f25 1
knit + f26 1
knit + f27 1
knit + f28 1
knit + f29 1
knit + f30 1
knit - f30 1
knit - f29 1
knit - f28 1
knit - f27 1
knit - f26 1
knit - f25 1
knit - f24 1
knit - f23 1
knit - f22 1
knit - f21 1
knit - f20 1
knit - f19 1
knit - f18 1
knit - f17 1
knit - f16 1
knit - f15 1
knit - f14 1
knit - f13 1
knit - f12 1
knit - f11 1
knit - f10 1
knit - f9 1
knit - f8 1
knit - f7 1
knit - f6 1
knit - f5 1
knit - f4 1
knit - f3 1
knit - f2 1
knit - f1 1
knit - f0 1
knit + f0 1
knit + f1 1
knit + f2 1
knit + f3 1
knit + f4 1
knit + f5 1
knit + f6 1
knit + f7 1
knit + f8 1
knit + f9 1
knit + f10 1
knit + f11 1
knit + f12 1
knit + f13 1
knit + f14 1
knit + f15 1
knit + f16 1
knit + f17 1
knit + f18 1
knit + f19 1
knit + f20 1
knit + f21 1
knit + f22 1
knit + f23 1
knit + f24 1
knit + f25 1
knit + f26 1
knit + f27 1
knit + f28 1
knit + f29 1
knit + f30 1
knit - f30 1
knit - f29 1
knit - f28 1
knit - f27 1
knit - f26 1
knit - f25 1
knit - f24 1
knit - f23 1
knit - f22 1
knit - f21 1
knit - f20 1
knit - f19 1
knit - f18 1
knit - f17 1
knit - f16 1
knit - f15 1
knit - f14 1
knit - f13 1
knit - f12 1
knit - f11 1
knit - f10 1
knit - f9 1
knit - f8 1
knit - f7 1
knit - f6 1
knit - f5 1
knit - f4 1
knit - f3 1
knit - f2 1
knit - f1 1
knit - f0 1
knit + f0 1
knit + f1 1
knit + f2 1
knit + f3 1
knit + f4 1
knit + f5 1
knit + f6 1
knit + f7 1
knit + f8 1
knit + f9 1
knit + f10 1
knit + f11 1
knit + f12 1
knit + f13 1
knit + f14 1
knit + f15 1
knit + f16 1
knit + f17 1
knit + f18 1
knit + f19 1
knit + f20 1
knit + f21 1
knit + f22 1
knit + f23 1
knit + f24 1
knit + f25 1
knit + f26 1
knit + f27 1
knit + f28 1
knit + f29 1
knit + f30 1
knit - f30 1
knit - f29 1
knit - f28 1
knit - f27 1
knit - f26 1
knit - f25 1
knit - f24 1
knit - f23 1
knit - f22 1
knit - f21 1
knit - f20 1
knit - f19 1
knit - f18 1
knit - f17 1
knit - f16 1
knit - f15 1
knit - f14 1
knit - f13 1
knit - f12 1
knit - f11 1
knit - f10 1
knit - f9 1
knit - f8 1
knit - f7 1
knit - f6 1
knit - f5 1
knit - f4 1
knit - f3 1
knit - f2 1
knit - f1 1
knit - f0 1
knit + f0 1
knit + f1 1
knit + f2 1
knit + f3 1
knit + f4 1
knit + f5 1
knit + f6 1
knit + f7 1
knit + f8 1
knit + f9 1
knit + f10 1
knit + f11 1
knit + f12 1
knit + f13 1
knit + f14 1
knit + f15 1
knit + f16 1
knit + f17 1
knit + f18 1
knit + f19 1
knit + f20 1
knit + f21 1
knit + f22 1
knit + f23 1
knit + f24 1
knit + f25 1
knit + f26 1
knit + f27 1
knit + f28 1
knit + f29 1
knit + f30 1
;end jersey
;begin rib (ffb)
knit - f30 1
knit - b29 1
knit - f28 1
knit - f27 1
knit - b26 1
knit - f25 1
knit - f24 1
knit - b23 1
knit - f22 1
knit - f21 1
knit - b20 1
knit - f19 1
knit - f18 1
knit - b17 1
knit - f16 1
knit - f15 1
knit - b14 1
knit - f13 1
knit - f12 1
knit - b11 1
knit - f10 1
knit - f9 1
knit - b8 1
knit - f7 1
knit - f6 1
knit - b5 1
knit - f4 1
knit - f3 1
knit - b2 1
knit - f1 1
knit - f0 1
knit + f0 1
knit + f1 1
knit + b2 1
knit + f3 1
knit + f4 1
knit + b5 1
knit + f6 1
knit + f7 1
knit + b8 1
knit + f9 1
knit + f10 1
knit + b11 1
knit + f12 1
knit + f13 1
knit + b14 1
knit + f15 1
knit + f16 1
knit + b17 1
knit + f18 1
knit + f19 1
knit + b20 1
knit + f21 1
knit + f22 1
knit + b23 1
knit + f24 1
knit + f25 1
knit + b26 1
knit + f27 1
knit + f28 1
knit + b29 1
knit + f30 1
knit - f30 1
knit - b29 1
knit - f28 1
knit - f27 1
knit - b26 1
knit - f25 1
knit - f24 1
knit - b23 1
knit - f22 1
knit - f21 1
knit - b20 1
knit - f19 1
knit - f18 1
knit - b17 1
knit - f16 1
knit - f15 1
knit - b14 1
knit - f13 1
knit - f12 1
knit - b11 1
knit - f10 1
knit - f9 1
knit - b8 1
knit - f7 1
knit - f6 1
knit - b5 1
knit - f4 1
knit - f3 1
knit - b2 1
knit - f1 1
knit - f0 1
knit + f0 1
knit + f1 1
knit + b2 1
knit + f3 1
knit + f4 1
knit + b5 1
knit + f6 1
knit + f7 1
knit + b8 1
knit + f9 1
knit + f10 1
knit + b11 1
knit + f12 1
knit + f13 1
knit + b14 1
knit + f15 1
knit + f16 1
knit + b17 1
knit + f18 1
knit + f19 1
knit + b20 1
knit + f21 1
knit + f22 1
knit + b23 1
knit + f24 1
knit + f25 1
knit + b26 1
knit + f27 1
knit + f28 1
knit + b29 1
knit + f30 1
knit - f30 1
knit - b29 1
knit - f28 1
knit - f27 1
knit - b26 1
knit - f25 1
knit - f24 1
knit - b23 1
knit - f22 1
knit - f21 1
knit - b20 1
knit - f19 1
knit - f18 1
knit - b17 1
knit - f16 1
knit - f15 1
knit - b14 1
knit - f13 1
knit - f12 1
knit - b11 1
knit - f10 1
knit - f9 1
knit - b8 1
knit - f7 1
knit - f6 1
knit - b5 1
knit - f4 1
knit - f3 1
knit - b2 1
knit - f1 1
knit - f0 1
knit + f0 1
knit + f1 1
knit + b2 1
knit + f3 1
knit + f4 1
knit + b5 1
knit + f6 1
knit + f7 1
knit + b8 1
knit + f9 1
knit + f10 1
knit + b11 1
knit + f12 1
knit + f13 1
knit + b14 1
knit + f15 1
knit + f16 1
knit + b17 1
knit + f18 1
knit + f19 1
knit + b20 1
knit + f21 1
knit + f22 1
knit + b23 1
knit + f24 1
knit + f25 1
knit + b26 1
knit + f27 1
knit + f28 1
knit + b29 1
knit + f30 1
knit - f30 1
knit - b29 1
knit - f28 1
knit - f27 1
knit - b26 1
knit - f25 1
knit - f24 1
knit - b23 1
knit - f22 1
knit - f21 1
knit - b20 1
knit - f19 1
knit - f18 1
knit - b17 1
knit - f16 1
knit - f15 1
knit - b14 1
knit - f13 1
knit - f12 1
knit - b11 1
knit - f10 1
knit - f9 1
knit - b8 1
knit - f7 1
knit - f6 1
knit - b5 1
knit - f4 1
knit - f3 1
knit - b2 1
knit - f1 1
knit - f0 1
knit + f0 1
knit + f1 1
knit + b2 1
knit + f3 1
knit + f4 1
knit + b5 1
knit + f6 1
knit + f7 1
knit + b8 1
knit + f9 1
knit + f10 1
knit + b11 1
knit + f12 1
knit + f13 1
knit + b14 1
knit + f15 1
knit + f16 1
knit + b17 1
knit + f18 1
knit + f19 1
knit + b20 1
knit + f21 1
knit + f22 1
knit + b23 1
knit + f24 1
knit + f25 1
knit + b26 1
knit + f27 1
knit + f28 1
knit + b29 1
knit + f30 1
knit - f30 1
knit - b29 1
knit - f28 1
knit - f27 1
knit - b26 1
knit - f25 1
knit - f24 1
knit - b23 1
knit - f22 1
knit - f21 1
knit - b20 1
knit - f19 1
knit - f18 1
knit - b17 1
knit - f16 1
knit - f15 1
knit - b14 1
knit - f13 1
knit - f12 1
knit - b11 1
knit - f10 1
knit - f9 1
knit - b8 1
knit - f7 1
knit - f6 1
knit - b5 1
knit - f4 1
knit - f3 1
knit - b2 1
knit - f1 1
knit - f0 1
knit + f0 1
knit + f1 1
knit + b2 1
knit + f3 1
knit + f4 1
knit + b5 1
knit + f6 1
knit + f7 1
knit + b8 1
knit + f9 1
knit + f10 1
knit + b11 1
knit + f12 1
knit + f13 1
knit + b14 1
knit + f15 1
knit + f16 1
knit + b17 1
knit + f18 1
knit + f19 1
knit + b20 1
knit + f21 1
knit + f22 1
knit + b23 1
knit + f24 1
knit + f25 1
knit + b26 1
knit + f27 1
knit + f28 1
knit + b29 1
knit + f30 1
knit - f30 1
knit - b29 1
knit - f28 1
knit - f27 1
knit - b26 1
knit - f25 1
knit - f24 1
knit - b23 1
knit - f22 1
knit - f21 1
knit - b20 1
knit - f19 1
knit - f18 1
knit - b17 1
knit - f16 1
knit - f15 1
knit - b14 1
knit - f13 1
knit - f12 1
knit - b11 1
knit - f10 1
knit - f9 1
knit - b8 1
knit - f7 1
knit - f6 1
knit - b5 1
knit - f4 1
knit - f3 1
knit - b2 1
knit - f1 1
knit - f0 1
knit + f0 1
knit + f1 1
knit + b2 1
knit + f3 1
knit + f4 1
knit + b5 1
knit + f6 1
knit + f7 1
knit + b8 1
knit + f9 1
knit + f10 1
knit + b11 1
knit + f12 1
knit + f13 1
knit + b14 1
knit + f15 1
knit + f16 1
knit + b17 1
knit + f18 1
knit + f19 1
knit + b20 1
knit + f21 1
knit + f22 1
knit + b23 1
knit + f24 1
knit + f25 1
knit + b26 1
knit + f27 1
knit + f28 1
knit + b29 1
knit + f30 1
knit - f30 1
knit - b29 1
knit - f28 1
knit - f27 1
knit - b26 1
knit - f25 1
knit - f24 1
knit - b23 1
knit - f22 1
knit - f21 1
knit - b20 1
knit - f19 1
knit - f18 1
knit - b17 1
knit - f16 1
knit - f15 1
knit - b14 1
knit - f13 1
knit - f12 1
knit - b11 1
knit - f10 1
knit - f9 1
knit - b8 1
knit - f7 1
knit - f6 1
knit - b5 1
knit - f4 1
knit - f3 1
knit - b2 1
knit - f1 1
knit - f0 1
knit + f0 1
knit + f1 1
knit + b2 1
knit + f3 1
knit + f4 1
knit + b5 1
knit + f6 1
knit + f7 1
knit + b8 1
knit + f9 1
knit + f10 1
knit + b11 1
knit + f12 1
knit + f13 1
knit + b14 1
knit + f15 1
knit + f16 1
knit + b17 1
knit + f18 1
knit + f19 1
knit + b20 1
knit + f21 1
knit + f22 1
knit + b23 1
knit + f24 1
knit + f25 1
knit + b26 1
knit + f27 1
knit + f28 1
knit + b29 1
knit + f30 1
knit - f30 1
knit - b29 1
knit - f28 1
knit - f27 1
knit - b26 1
knit - f25 1
knit - f24 1
knit - b23 1
knit - f22 1
knit - f21 1
knit - b20 1
knit - f19 1
knit - f18 1
knit - b17 1
knit - f16 1
knit - f15 1
knit - b14 1
knit - f13 1
knit - f12 1
knit - b11 1
knit - f10 1
knit - f9 1
knit - b8 1
knit - f7 1
knit - f6 1
knit - b5 1
knit - f4 1
knit - f3 1
knit - b2 1
knit - f1 1
knit - f0 1
knit + f0 1
knit + f1 1
knit + b2 1
knit + f3 1
knit + f4 1
knit + b5 1
knit + f6 1
knit + f7 1
knit + b8 1
knit + f9 1
knit + f10 1
knit + b11 1
knit + f12 1
knit + f13 1
knit + b14 1
knit + f15 1
knit + f16 1
knit + b17 1
knit + f18 1
knit + f19 1
knit + b20 1
knit + f21 1
knit + f22 1
knit + b23 1
knit + f24 1
knit + f25 1
knit + b26 1
knit + f27 1
knit + f28 1
knit + b29 1
knit + f30 1
knit - f30 1
knit - b29 1
knit - f28 1
knit - f27 1
knit - b26 1
knit - f25 1
knit - f24 1
knit - b23 1
knit - f22 1
knit - f21 1
knit - b20 1
knit - f19 1
knit - f18 1
knit - b17 1
knit - f16 1
knit - f15 1
knit - b14 1
knit - f13 1
knit - f12 1
knit - b11 1
knit - f10 1
knit - f9 1
knit - b8 1
knit - f7 1
knit - f6 1
knit - b5 1
knit - f4 1
knit - f3 1
knit - b2 1
knit - f1 1
knit - f0 1
knit + f0 1
knit + f1 1
knit + b2 1
knit + f3 1
knit + f4 1
knit + b5 1
knit + f6 1
knit + f7 1
knit + b8 1
knit + f9 1
knit + f10 1
knit + b11 1
knit + f12 1
knit + f13 1
knit + b14 1
knit + f15 1
knit + f16 1
knit + b17 1
knit + f18 1
knit + f19 1
knit + b20 1
knit + f21 1
knit + f22 1
knit + b23 1
knit + f24 1
knit + f25 1
knit + b26 1
knit + f27 1
knit + f28 1
knit + b29 1
knit + f30 1
knit - f30 1
knit - b29 1
knit - f28 1
knit - f27 1
knit - b26 1
knit - f25 1
knit - f24 1
knit - b23 1
knit - f22 1
knit - f21 1
knit - b20 1
knit - f19 1
knit - f18 1
knit - b17 1
knit - f16 1
knit - f15 1
knit - b14 1
knit - f13 1
knit - f12 1
knit - b11 1
knit - f10 1
knit - f9 1
knit - b8 1
knit - f7 1
knit - f6 1
knit - b5 1
knit - f4 1
knit - f3 1
knit - b2 1
knit - f1 1
knit - f0 1
knit + f0 1
knit + f1 1
knit + b2 1
knit + f3 1
knit + f4 1
knit + b5 1
knit + f6 1
knit + f7 1
knit + b8 1
knit + f9 1
knit + f10 1
knit + b11 1
knit + f12 1
knit + f13 1
knit + b14 1
knit + f15 1
knit + f16 1
knit + b17 1
knit + f18 1
knit + f19 1
knit + b20 1
knit + f21 1
knit + f22 1
knit + b23 1
knit + f24 1
knit + f25 1
knit + b26 1
knit + f27 1
knit + f28 1
knit + b29 1
knit + f30 1
knit - f30 1
knit - b29 1
knit - f28 1
knit - f27 1
knit - b26 1
knit - f25 1
knit - f24 1
knit - b23 1
knit - f22 1
knit - f21 1
knit - b20 1
knit - f19 1
knit - f18 1
knit - b17 1
knit - f16 1
knit - f15 1
knit - b14 1
knit - f13 1
knit - f12 1
knit - b11 1
knit - f10 1
knit - f9 1
knit - b8 1
knit - f7 1
knit - f6 1
knit - b5 1
knit - f4 1
knit - f3 1
knit - b2 1
knit - f1 1
knit - f0 1
knit + f0 1
knit + f1 1
knit + b2 1
knit + f3 1
knit + f4 1
knit + b5 1
knit + f6 1
knit + f7 1
knit + b8 1
knit + f9 1
knit + f10 1
knit + b11 1
knit + f12 1
knit + f13 1
knit + b14 1
knit + f15 1
knit + f16 1
knit + b17 1
knit + f18 1
knit + f19 1
knit + b20 1
knit + f21 1
knit + f22 1
knit + b23 1
knit + f24 1
knit + f25 1
knit + b26 1
knit + f27 1
knit + f28 1
knit + b29 1
knit + f30 1
knit - f30 1
knit - b29 1
knit - f28 1
knit - f27 1
knit - b26 1
knit - f25 1
knit - f24 1
knit - b23 1
knit - f22 1
knit - f21 1
knit - b20 1
knit - f19 1
knit - f18 1
knit - b17 1
knit - f16 1
knit - f15 1
knit - b14 1
knit - f13 1
knit - f12 1
knit - b11 1
knit - f10 1
knit - f9 1
knit - b8 1
knit - f7 1
knit - f6 1
knit - b5 1
knit - f4 1
knit - f3 1
knit - b2 1
knit - f1 1
knit - f0 1
knit + f0 1
knit + f1 1
knit + b2 1
knit + f3 1
knit + f4 1
knit + b5 1
knit + f6 1
knit + f7 1
knit + b8 1
knit + f9 1
knit + f10 1
knit + b11 1
knit + f12 1
knit + f13 1
knit + b14 1
knit + f15 1
knit + f16 1
knit + b17 1
knit + f18 1
knit + f19 1
knit + b20 1
knit + f21 1
knit + f22 1
knit + b23 1
knit + f24 1
knit + f25 1
knit + b26 1
knit + f27 1
knit + f28 1
knit + b29 1
knit + f30 1
knit - f30 1
knit - b29 1
knit - f28 1
knit - f27 1
knit - b26 1
knit - f25 1
knit - f24 1
knit - b23 1
knit - f22 1
knit - f21 1
knit - b20 1
knit - f19 1
knit - f18 1
knit - b17 1
knit - f16 1
knit - f15 1
knit - b14 1
knit - f13 1
knit - f12 1
knit - b11 1
knit - f10 1
knit - f9 1
knit - b8 1
knit - f7 1
knit - f6 1
knit - b5 1
knit - f4 1
knit - f3 1
knit - b2 1
knit - f1 1
knit - f0 1
knit + f0 1
knit + f1 1
knit + b2 1
knit + f3 1
knit + f4 1
knit + b5 1
knit + f6 1
knit + f7 1
knit + b8 1
knit + f9 1
knit + f10 1
knit + b11 1
knit + f12 1
knit + f13 1
knit + b14 1
knit + f15 1
knit + f16 1
knit + b17 1
knit + f18 1
knit + f19 1
knit + b20 1
knit + f21 1
knit + f22 1
knit + b23 1
knit + f24 1
knit + f25 1
knit + b26 1
knit + f27 1
knit + f28 1
knit + b29 1
knit + f30 1
knit - f30 1
knit - b29 1
knit - f28 1
knit - f27 1
knit - b26 1
knit - f25 1
knit - f24 1
knit - b23 1
knit - f22 1
knit - f21 1
knit - b20 1
knit - f19 1
knit - f18 1
knit - b17 1
knit - f16 1
knit - f15 1
knit - b14 1
knit - f13 1
knit - f12 1
knit - b11 1
knit - f10 1
knit - f9 1
knit - b8 1
knit - f7 1
knit - f6 1
knit - b5 1
knit - f4 1
knit - f3 1
knit - b2 1
knit - f1 1
knit - f0 1
knit + f0 1
knit + f1 1
knit + b2 1
knit + f3 1
knit + f4 1
knit + b5 1
knit + f6 1
knit + f7 1
knit + b8 1
knit + f9 1
knit + f10 1
knit + b11 1
knit + f12 1
knit + f13 1
knit + b14 1
knit + f15 1
knit + f16 1
knit + b17 1
knit + f18 1
knit + f19 1
knit + b20 1
knit + f21 1
knit + f22 1
knit + b23 1
knit + f24 1
knit + f25 1
knit + b26 1
knit + f27 1
knit + f28 1
knit + b29 1
knit + f30 1
knit - f30 1
knit - b29 1
knit - f28 1
knit - f27 1
knit - b26 1
knit - f25 1
knit - f24 1
knit - b23 1
knit - f22 1
knit - f21 1
knit - b20 1
knit - f19 1
knit - f18 1
knit - b17 1
knit - f16 1
knit - f15 1
knit - b14 1
knit - f13 1
knit - f12 1
knit - b11 1
knit - f10 1
knit - f9 1
knit - b8 1
knit - f7 1
knit - f6 1
knit - b5 1
knit - f4 1
knit - f3 1
knit - b2 1
knit - f1 1
knit - f0 1
knit + f0 1
knit + f1 1
knit + b2 1
knit + f3 1
knit + f4 1
knit + b5 1
knit + f6 1
knit + f7 1
knit + b8 1
knit + f9 1
knit + f10 1
knit + b11 1
knit + f12 1
knit + f13 1
knit + b14 1
knit + f15 1
knit + f16 1
knit + b17 1
knit + f18 1
knit + f19 1
knit + b20 1
knit + f21 1
knit + f22 1
knit + b23 1
knit + f24 1
knit + f25 1
knit + b26 1
knit + f27 1
knit + f28 1
knit + b29 1
knit + f30 1
;end rib
;begin 3x3 garter
knit - f30 1
knit - f29 1
knit - f28 1
knit - f27 1
knit - f26 1
knit - f25 1
knit - f24 1
knit - f23 1
knit - f22 1
knit - f21 1
knit - f20 1
knit - f19 1
knit - f18 1
knit - f17 1
knit - f16 1
knit - f15 1
knit - f14 1
knit - f13 1
knit - f12 1
knit - f11 1
knit - f10 1
knit - f9 1
knit - f8 1
knit - f7 1
knit - f6 1
knit - f5 1
knit - f4 1
knit - f3 1
knit - f2 1
knit - f1 1
knit - f0 1
xfer f29 b29
xfer f28 b28
xfer f27 b27
xfer f26 b26
xfer f25 b25
xfer f24 b24
xfer f23 b23
xfer f22 b22
xfer f21 b21
xfer f20 b20
xfer f19 b19
xfer f18 b18
xfer f17 b17
xfer f16 b16
xfer f15 b15
xfer f14 b14
xfer f13 b13
xfer f12 b12
xfer f11 b11
xfer f10 b10
xfer f9 b9
xfer f8 b8
xfer f7 b7
xfer f6 b6
xfer f5 b5
xfer f4 b4
xfer f3 b3
xfer f2 b2
xfer f1 b1
knit + f0 1
knit + b1 1
knit + b2 1
knit + b3 1
knit + b4 1
knit + b5 1
knit + b6 1
knit + b7 1
knit + b8 1
knit + b9 1
knit + b10 1
knit + b11 1
knit + b12 1
knit + b13 1
knit + b14 1
knit + b15 1
knit + b16 1
knit + b17 1
knit + b18 1
knit + b19 1
knit + b20 1
knit + b21 1
knit + b22 1
knit + b23 1
knit + b24 1
knit + b25 1
knit + b26 1
knit + b27 1
knit + b28 1
knit + b29 1
knit + f30 1
xfer b30 f30
xfer b29 f29
xfer b28 f28
xfer b27 f27
xfer b26 f26
xfer b25 f25
xfer b24 f24
xfer b23 f23
xfer b22 f22
xfer b21 f21
xfer b20 f20
xfer b19 f19
xfer b18 f18
xfer b17 f17
xfer b16 f16
xfer b15 f15
xfer b14 f14
xfer b13 f13
xfer b12 f12
xfer b11 f11
xfer b10 f10
xfer b9 f9
xfer b8 f8
xfer b7 f7
xfer b6 f6
xfer b5 f5
xfer b4 f4
xfer b3 f3
xfer b2 f2
xfer b1 f1
xfer b0 f0
knit - f30 1
knit - f29 1
knit - f28 1
knit - f27 1
knit - f26 1
knit - f25 1
knit - f24 1
knit - f23 1
knit - f22 1
knit - f21 1
knit - f20 1
knit - f19 1
knit - f18 1
knit - f17 1
knit - f16 1
knit - f15 1
knit - f14 1
knit - f13 1
knit - f12 1
knit - f11 1
knit - f10 1
knit - f9 1
knit - f8 1
knit - f7 1
knit - f6 1
knit - f5 1
knit - f4 1
knit - f3 1
knit - f2 1
knit - f1 1
knit - f0 1
knit + f0 1
knit + f1 1
knit + f2 1
knit + f3 1
knit + f4 1
knit + f5 1
knit + f6 1
knit + f7 1
knit + f8 1
knit + f9 1
knit + f10 1
knit + f11 1
knit + f12 1
knit + f13 1
knit + f14 1
knit + f15 1
knit + f16 1
knit + f17 1
knit + f18 1
knit + f19 1
knit + f20 1
knit + f21 1
knit + f22 1
knit + f23 1
knit + f24 1
knit + f25 1
knit + f26 1
knit + f27 1
knit + f28 1
knit + f29 1
knit + f30 1
xfer f29 b29
xfer f28 b28
xfer f27 b27
xfer f26 b26
xfer f25 b25
xfer f24 b24
xfer f23 b23
xfer f22 b22
xfer f21 b21
xfer f20 b20
xfer f19 b19
xfer f18 b18
xfer f17 b17
xfer f16 b16
xfer f15 b15
xfer f14 b14
xfer f13 b13
xfer f12 b12
xfer f11 b11
xfer f10 b10
xfer f9 b9
xfer f8 b8
xfer f7 b7
xfer f6 b6
xfer f5 b5
xfer f4 b4
xfer f3 b3
xfer f2 b2
xfer f1 b1
knit - f30 1
knit - b29 1
knit - b28 1
knit - b27 1
knit - b26 1
knit - b25 1
knit - b24 1
knit - b23 1
knit - b22 1
knit - b21 1
knit - b20 1
knit - b19 1
knit - b18 1
knit - b17 1
knit - b16 1
knit - b15 1
knit - b14 1
knit - b13 1
knit - b12 1
knit - b11 1
knit - b10 1
knit - b9 1
knit - b8 1
knit - b7 1
knit - b6 1
knit - b5 1
knit - b4 1
knit - b3 1
knit - b2 1
knit - b1 1
knit - f0 1
knit + f0 1
knit + b1 1
knit + b2 1
knit + b3 1
knit + b4 1
knit + b5 1
knit + b6 1
knit + b7 1
knit + b8 1
knit + b9 1
knit + b10 1
knit + b11 1
knit + b12 1
knit + b13 1
knit + b14 1
knit + b15 1
knit + b16 1
knit + b17 1
knit + b18 1
knit + b19 1
knit + b20 1
knit + b21 1
knit + b22 1
knit + b23 1
knit + b24 1
knit + b25 1
knit + b26 1
knit + b27 1
knit + b28 1
knit + b29 1
knit + f30 1
xfer b30 f30
xfer b29 f29
xfer b28 f28
xfer b27 f27
xfer b26 f26
xfer b25 f25
xfer b24 f24
xfer b23 f23
xfer b22 f22
xfer b21 f21
xfer b20 f20
xfer b19 f19
xfer b18 f18
xfer b17 f17
xfer b16 f16
xfer b15 f15
xfer b14 f14
xfer b13 f13
xfer b12 f12
xfer b11 f11
xfer b10 f10
xfer b9 f9
xfer b8 f8
xfer b7 f7
xfer b6 f6
xfer b5 f5
xfer b4 f4
xfer b3 f3
xfer b2 f2
xfer b1 f1
xfer b0 f0
knit - f30 1
knit - f29 1
knit - f28 1
knit - f27 1
knit - f26 1
knit - f25 1
knit - f24 1
knit - f23 1
knit - f22 1
knit - f21 1
knit - f20 1
knit - f19 1
knit - f18 1
knit - f17 1
knit - f16 1
knit - f15 1
knit - f14 1
knit - f13 1
knit - f12 1
knit - f11 1
knit - f10 1
knit - f9 1
knit - f8 1
knit - f7 1
knit - f6 1
knit - f5 1
knit - f4 1
knit - f3 1
knit - f2 1
knit - f1 1
knit - f0 1
xfer f29 b29
xfer f28 b28
xfer f27 b27
xfer f26 b26
xfer f25 b25
xfer f24 b24
xfer f23 b23
xfer f22 b22
xfer f21 b21
xfer f20 b20
xfer f19 b19
xfer f18 b18
xfer f17 b17
xfer f16 b16
xfer f15 b15
xfer f14 b14
xfer f13 b13
xfer f12 b12
xfer f11 b11
xfer f10 b10
xfer f9 b9
xfer f8 b8
xfer f7 b7
xfer f6 b6
xfer f5 b5
xfer f4 b4
xfer f3 b3
xfer f2 b2
xfer f1 b1
knit + f0 1
knit + b1 1
knit + b2 1
knit + b3 1
knit + b4 1
knit + b5 1
knit + b6 1
knit + b7 1
knit + b8 1
knit + b9 1
knit + b10 1
knit + b11 1
knit + b12 1
knit + b13 1
knit + b14 1
knit + b15 1
knit + b16 1
knit + b17 1
knit + b18 1
knit + b19 1
knit + b20 1
knit + b21 1
knit + b22 1
knit + b23 1
knit + b24 1
knit + b25 1
knit + b26 1
knit + b27 1
knit + b28 1
knit + b29 1
knit + f30 1
xfer b30 f30
xfer b29 f29
xfer b28 f28
xfer b27 f27
xfer b26 f26
xfer b25 f25
xfer b24 f24
xfer b23 f23
xfer b22 f22
xfer b21 f21
xfer b20 f20
xfer b19 f19
xfer b18 f18
xfer b17 f17
xfer b16 f16
xfer b15 f15
xfer b14 f14
xfer b13 f13
xfer b12 f12
xfer b11 f11
xfer b10 f10
xfer b9 f9
xfer b8 f8
xfer b7 f7
xfer b6 f6
xfer b5 f5
xfer b4 f4
xfer b3 f3
xfer b2 f2
xfer b1 f1
xfer b0 f0
knit - f30 1
knit - f29 1
knit - f28 1
knit - f27 1
knit - f26 1
knit - f25 1
knit - f24 1
knit - f23 1
knit - f22 1
knit - f21 1
knit - f20 1
knit - f19 1
knit - f18 1
knit - f17 1
knit - f16 1
knit - f15 1
knit - f14 1
knit - f13 1
knit - f12 1
knit - f11 1
knit - f10 1
knit - f9 1
knit - f8 1
knit - f7 1
knit - f6 1
knit - f5 1
knit - f4 1
knit - f3 1
knit - f2 1
knit - f1 1
knit - f0 1
knit + f0 1
knit + f1 1
knit + f2 1
knit + f3 1
knit + f4 1
knit + f5 1
knit + f6 1
knit + f7 1
knit + f8 1
knit + f9 1
knit + f10 1
knit + f11 1
knit + f12 1
knit + f13 1
knit + f14 1
knit + f15 1
knit + f16 1
knit + f17 1
knit + f18 1
knit + f19 1
knit + f20 1
knit + f21 1
knit + f22 1
knit + f23 1
knit + f24 1
knit + f25 1
knit + f26 1
knit + f27 1
knit + f28 1
knit + f29 1
knit + f30 1
xfer f29 b29
xfer f28 b28
xfer f27 b27
xfer f26 b26
xfer f25 b25
xfer f24 b24
xfer f23 b23
xfer f22 b22
xfer f21 b21
xfer f20 b20
xfer f19 b19
xfer f18 b18
xfer f17 b17
xfer f16 b16
xfer f15 b15
xfer f14 b14
xfer f13 b13
xfer f12 b12
xfer f11 b11
xfer f10 b10
xfer f9 b9
xfer f8 b8
xfer f7 b7
xfer f6 b6
xfer f5 b5
xfer f4 b4
xfer f3 b3
xfer f2 b2
xfer f1 b1
knit - f30 1
knit - b29 1
knit - b28 1
knit - b27 1
knit - b26 1
knit - b25 1
knit - b24 1
knit - b23 1
knit - b22 1
knit - b21 1
knit - b20 1
knit - b19 1
knit - b18 1
knit - b17 1
knit - b16 1
knit - b15 1
knit - b14 1
knit - b13 1
knit - b12 1
knit - b11 1
knit - b10 1
knit - b9 1
knit - b8 1
knit - b7 1
knit - b6 1
knit - b5 1
knit - b4 1
knit - b3 1
knit - b2 1
knit - b1 1
knit - f0 1
knit + f0 1
knit + b1 1
knit + b2 1
knit + b3 1
knit + b4 1
knit + b5 1
knit + b6 1
knit + b7 1
knit + b8 1
knit + b9 1
knit + b10 1
knit + b11 1
knit + b12 1
knit + b13 1
knit + b14 1
knit + b15 1
knit + b16 1
knit + b17 1
knit + b18 1
knit + b19 1
knit + b20 1
knit + b21 1
knit + b22 1
knit + b23 1
knit + b24 1
knit + b25 1
knit + b26 1
knit + b27 1
knit + b28 1
knit + b29 1
knit + f30 1
xfer b30 f30
xfer b29 f29
xfer b28 f28
xfer b27 f27
xfer b26 f26
xfer b25 f25
xfer b24 f24
xfer b23 f23
xfer b22 f22
xfer b21 f21
xfer b20 f20
xfer b19 f19
xfer b18 f18
xfer b17 f17
xfer b16 f16
xfer b15 f15
xfer b14 f14
xfer b13 f13
xfer b12 f12
xfer b11 f11
xfer b10 f10
xfer b9 f9
xfer b8 f8
xfer b7 f7
xfer b6 f6
xfer b5 f5
xfer b4 f4
xfer b3 f3
xfer b2 f2
xfer b1 f1
xfer b0 f0
knit - f30 1
knit - f29 1
knit - f28 1
knit - f27 1
knit - f26 1
knit - f25 1
knit - f24 1
knit - f23 1
knit - f22 1
knit - f21 1
knit - f20 1
knit - f19 1
knit - f18 1
knit - f17 1
knit - f16 1
knit - f15 1
knit - f14 1
knit - f13 1
knit - f12 1
knit - f11 1
knit - f10 1
knit - f9 1
knit - f8 1
knit - f7 1
knit - f6 1
knit - f5 1
knit - f4 1
knit - f3 1
knit - f2 1
knit - f1 1
knit - f0 1
xfer f29 b29
xfer f28 b28
xfer f27 b27
xfer f26 b26
xfer f25 b25
xfer f24 b24
xfer f23 b23
xfer f22 b22
xfer f21 b21
xfer f20 b20
xfer f19 b19
xfer f18 b18
xfer f17 b17
xfer f16 b16
xfer f15 b15
xfer f14 b14
xfer f13 b13
xfer f12 b12
xfer f11 b11
xfer f10 b10
xfer f9 b9
xfer f8 b8
xfer f7 b7
xfer f6 b6
xfer f5 b5
xfer f4 b4
xfer f3 b3
xfer f2 b2
xfer f1 b1
knit + f0 1
knit + b1 1
knit + b2 1
knit + b3 1
knit + b4 1
knit + b5 1
knit + b6 1
knit + b7 1
knit + b8 1
knit + b9 1
knit + b10 1
knit + b11 1
knit + b12 1
knit + b13 1
knit + b14 1
knit + b15 1
knit + b16 1
knit + b17 1
knit + b18 1
knit + b19 1
knit + b20 1
knit + b21 1
knit + b22 1
knit + b23 1
knit + b24 1
knit + b25 1
knit + b26 1
knit + b27 1
knit + b28 1
knit + b29 1
knit + f30 1
xfer b30 f30
xfer b29 f29
xfer b28 f28
xfer b27 f27
xfer b26 f26
xfer b25 f25
xfer b24 f24
xfer b23 f23
xfer b22 f22
xfer b21 f21
xfer b20 f20
xfer b19 f19
xfer b18 f18
xfer b17 f17
xfer b16 f16
xfer b15 f15
xfer b14 f14
xfer b13 f13
xfer b12 f12
xfer b11 f11
xfer b10 f10
xfer b9 f9
xfer b8 f8
xfer b7 f7
xfer b6 f6
xfer b5 f5
xfer b4 f4
xfer b3 f3
xfer b2 f2
xfer b1 f1
xfer b0 f0
knit - f30 1
knit - f29 1
knit - f28 1
knit - f27 1
knit - f26 1
knit - f25 1
knit - f24 1
knit - f23 1
knit - f22 1
knit - f21 1
knit - f20 1
knit - f19 1
knit - f18 1
knit - f17 1
knit - f16 1
knit - f15 1
knit - f14 1
knit - f13 1
knit - f12 1
knit - f11 1
knit - f10 1
knit - f9 1
knit - f8 1
knit - f7 1
knit - f6 1
knit - f5 1
knit - f4 1
knit - f3 1
knit - f2 1
knit - f1 1
knit - f0 1
knit + f0 1
knit + f1 1
knit + f2 1
knit + f3 1
knit + f4 1
knit + f5 1
knit + f6 1
knit + f7 1
knit + f8 1
knit + f9 1
knit + f10 1
knit + f11 1
knit + f12 1
knit + f13 1
knit + f14 1
knit + f15 1
knit + f16 1
knit + f17 1
knit + f18 1
knit + f19 1
knit + f20 1
knit + f21 1
knit + f22 1
knit + f23 1
knit + f24 1
knit + f25 1
knit + f26 1
knit + f27 1
knit + f28 1
knit + f29 1
knit + f30 1
xfer f29 b29
xfer f28 b28
xfer f27 b27
xfer f26 b26
xfer f25 b25
xfer f24 b24
xfer f23 b23
xfer f22 b22
xfer f21 b21
xfer f20 b20
xfer f19 b19
xfer f18 b18
xfer f17 b17
xfer f16 b16
xfer f15 b15
xfer f14 b14
xfer f13 b13
xfer f12 b12
xfer f11 b11
xfer f10 b10
xfer f9 b9
xfer f8 b8
xfer f7 b7
xfer f6 b6
xfer f5 b5
xfer f4 b4
xfer f3 b3
xfer f2 b2
xfer f1 b1
knit - f30 1
knit - b29 1
knit - b28 1
knit - b27 1
knit - b26 1
knit - b25 1
knit - b24 1
knit - b23 1
knit - b22 1
knit - b21 1
knit - b20 1
knit - b19 1
knit - b18 1
knit - b17 1
knit - b16 1
knit - b15 1
knit - b14 1
knit - b13 1
knit - b12 1
knit - b11 1
knit - b10 1
knit - b9 1
knit - b8 1
knit - b7 1
knit - b6 1
knit - b5 1
knit - b4 1
knit - b3 1
knit - b2 1
knit - b1 1
knit - f0 1
knit + f0 1
knit + b1 1
knit + b2 1
knit + b3 1
knit + b4 1
knit + b5 1
knit + b6 1
knit + b7 1
knit + b8 1
knit + b9 1
knit + b10 1
knit + b11 1
knit + b12 1
knit + b13 1
knit + b14 1
knit + b15 1
knit + b16 1
knit + b17 1
knit + b18 1
knit + b19 1
knit + b20 1
knit + b21 1
knit + b22 1
knit + b23 1
knit + b24 1
knit + b25 1
knit + b26 1
knit + b27 1
knit + b28 1
knit + b29 1
knit + f30 1
xfer b30 f30
xfer b29 f29
xfer b28 f28
xfer b27 f27
xfer b26 f26
xfer b25 f25
xfer b24 f24
xfer b23 f23
xfer b22 f22
xfer b21 f21
xfer b20 f20
xfer b19 f19
xfer b18 f18
xfer b17 f17
xfer b16 f16
xfer b15 f15
xfer b14 f14
xfer b13 f13
xfer b12 f12
xfer b11 f11
xfer b10 f10
xfer b9 f9
xfer b8 f8
xfer b7 f7
xfer b6 f6
xfer b5 f5
xfer b4 f4
xfer b3 f3
xfer b2 f2
xfer b1 f1
xfer b0 f0
knit - f30 1
knit - f29 1
knit - f28 1
knit - f27 1
knit - f26 1
knit - f25 1
knit - f24 1
knit - f23 1
knit - f22 1
knit - f21 1
knit - f20 1
knit - f19 1
knit - f18 1
knit - f17 1
knit - f16 1
knit - f15 1
knit - f14 1
knit - f13 1
knit - f12 1
knit - f11 1
knit - f10 1
knit - f9 1
knit - f8 1
knit - f7 1
knit - f6 1
knit - f5 1
knit - f4 1
knit - f3 1
knit - f2 1
knit - f1 1
knit - f0 1
xfer f29 b29
xfer f28 b28
xfer f27 b27
xfer f26 b26
xfer f25 b25
xfer f24 b24
xfer f23 b23
xfer f22 b22
xfer f21 b21
xfer f20 b20
xfer f19 b19
xfer f18 b18
xfer f17 b17
xfer f16 b16
xfer f15 b15
xfer f14 b14
xfer f13 b13
xfer f12 b12
xfer f11 b11
xfer f10 b10
xfer f9 b9
xfer f8 b8
xfer f7 b7
xfer f6 b6
xfer f5 b5
xfer f4 b4
xfer f3 b3
xfer f2 b2
xfer f1 b1
knit + f0 1
knit + b1 1
knit + b2 1
knit + b3 1
knit + b4 1
knit + b5 1
knit + b6 1
knit + b7 1
knit + b8 1
knit + b9 1
knit + b10 1
knit + b11 1
knit + b12 1
knit + b13 1
knit + b14 1
knit + b15 1
knit + b16 1
knit + b17 1
knit + b18 1
knit + b19 1
knit + b20 1
knit + b21 1
knit + b22 1
knit + b23 1
knit + b24 1
knit + b25 1
knit + b26 1
knit + b27 1
knit + b28 1
knit + b29 1
knit + f30 1
xfer b30 f30
xfer b29 f29
xfer b28 f28
xfer b27 f27
xfer b26 f26
xfer b25 f25
xfer b24 f24
xfer b23 f23
xfer b22 f22
xfer b21 f21
xfer b20 f20
xfer b19 f19
xfer b18 f18
xfer b17 f17
xfer b16 f16
xfer b15 f15
xfer b14 f14
xfer b13 f13
xfer b12 f12
xfer b11 f11
xfer b10 f10
xfer b9 f9
xfer b8 f8
xfer b7 f7
xfer b6 f6
xfer b5 f5
xfer b4 f4
xfer b3 f3
xfer b2 f2
xfer b1 f1
xfer b0 f0
knit - f30 1
knit - f29 1
knit - f28 1
knit - f27 1
knit - f26 1
knit - f25 1
knit - f24 1
knit - f23 1
knit - f22 1
knit - f21 1
knit - f20 1
knit - f19 1
knit - f18 1
knit - f17 1
knit - f16 1
knit - f15 1
knit - f14 1
knit - f13 1
knit - f12 1
knit - f11 1
knit - f10 1
knit - f9 1
knit - f8 1
knit - f7 1
knit - f6 1
knit - f5 1
knit - f4 1
knit - f3 1
knit - f2 1
knit - f1 1
knit - f0 1
knit + f0 1
knit + f1 1
knit + f2 1
knit + f3 1
knit + f4 1
knit + f5 1
knit + f6 1
knit + f7 1
knit + f8 1
knit + f9 1
knit + f10 1
knit + f11 1
knit + f12 1
knit + f13 1
knit + f14 1
knit + f15 1
knit + f16 1
knit + f17 1
knit + f18 1
knit + f19 1
knit + f20 1
knit + f21 1
knit + f22 1
knit + f23 1
knit + f24 1
knit + f25 1
knit + f26 1
knit + f27 1
knit + f28 1
knit + f29 1
knit + f30 1
xfer f29 b29
xfer f28 b28
xfer f27 b27
xfer f26 b26
xfer f25 b25
xfer f24 b24
xfer f23 b23
xfer f22 b22
xfer f21 b21
xfer f20 b20
xfer f19 b19
xfer f18 b18
xfer f17 b17
xfer f16 b16
xfer f15 b15
xfer f14 b14
xfer f13 b13
xfer f12 b12
xfer f11 b11
xfer f10 b10
xfer f9 b9
xfer f8 b8
xfer f7 b7
xfer f6 b6
xfer f5 b5
xfer f4 b4
xfer f3 b3
xfer f2 b2
xfer f1 b1
knit - f30 1
knit - b29 1
knit - b28 1
knit - b27 1
knit - b26 1
knit - b25 1
knit - b24 1
knit - b23 1
knit - b22 1
knit - b21 1
knit - b20 1
knit - b19 1
knit - b18 1
knit - b17 1
knit - b16 1
knit - b15 1
knit - b14 1
knit - b13 1
knit - b12 1
knit - b11 1
knit - b10 1
knit - b9 1
knit - b8 1
knit - b7 1
knit - b6 1
knit - b5 1
knit - b4 1
knit - b3 1
knit - b2 1
knit - b1 1
knit - f0 1
knit + f0 1
knit + b1 1
knit + b2 1
knit + b3 1
knit + b4 1
knit + b5 1
knit + b6 1
knit + b7 1
knit + b8 1
knit + b9 1
knit + b10 1
knit + b11 1
knit + b12 1
knit + b13 1
knit + b14 1
knit + b15 1
knit + b16 1
knit + b17 1
knit + b18 1
knit + b19 1
knit + b20 1
knit + b21 1
knit + b22 1
knit + b23 1
knit + b24 1
knit + b25 1
knit + b26 1
knit + b27 1
knit + b28 1
knit + b29 1
knit + f30 1
xfer b30 f30
xfer b29 f29
xfer b28 f28
xfer b27 f27
xfer b26 f26
xfer b25 f25
xfer b24 f24
xfer b23 f23
xfer b22 f22
xfer b21 f21
xfer b20 f20
xfer b19 f19
xfer b18 f18
xfer b17 f17
xfer b16 f16
xfer b15 f15
xfer b14 f14
xfer b13 f13
xfer b12 f12
xfer b11 f11
xfer b10 f10
xfer b9 f9
xfer b8 f8
xfer b7 f7
xfer b6 f6
xfer b5 f5
xfer b4 f4
xfer b3 f3
xfer b2 f2
xfer b1 f1
xfer b0 f0
knit - f30 1
knit - f29 1
knit - f28 1
knit - f27 1
knit - f26 1
knit - f25 1
knit - f24 1
knit - f23 1
knit - f22 1
knit - f21 1
knit - f20 1
knit - f19 1
knit - f18 1
knit - f17 1
knit - f16 1
knit - f15 1
knit - f14 1
knit - f13 1
knit - f12 1
knit - f11 1
knit - f10 1
knit - f9 1
knit - f8 1
knit - f7 1
knit - f6 1
knit - f5 1
knit - f4 1
knit - f3 1
knit - f2 1
knit - f1 1
knit - f0 1
xfer f29 b29
xfer f28 b28
xfer f27 b27
xfer f26 b26
xfer f25 b25
xfer f24 b24
xfer f23 b23
xfer f22 b22
xfer f21 b21
xfer f20 b20
xfer f19 b19
xfer f18 b18
xfer f17 b17
xfer f16 b16
xfer f15 b15
xfer f14 b14
xfer f13 b13
xfer f12 b12
xfer f11 b11
xfer f10 b10
xfer f9 b9
xfer f8 b8
xfer f7 b7
xfer f6 b6
xfer f5 b5
xfer f4 b4
xfer f3 b3
xfer f2 b2
xfer f1 b1
knit + f0 1
knit + b1 1
knit + b2 1
knit + b3 1
knit + b4 1
knit + b5 1
knit + b6 1
knit + b7 1
knit + b8 1
knit + b9 1
knit + b10 1
knit + b11 1
knit + b12 1
knit + b13 1
knit + b14 1
knit + b15 1
knit + b16 1
knit + b17 1
knit + b18 1
knit + b19 1
knit + b20 1
knit + b21 1
knit + b22 1
knit + b23 1
knit + b24 1
knit + b25 1
knit + b26 1
knit + b27 1
knit + b28 1
knit + b29 1
knit + f30 1
xfer b30 f30
xfer b29 f29
xfer b28 f28
xfer b27 f27
xfer b26 f26
xfer b25 f25
xfer b24 f24
xfer b23 f23
xfer b22 f22
xfer b21 f21
xfer b20 f20
xfer b19 f19
xfer b18 f18
xfer b17 f17
xfer b16 f16
xfer b15 f15
xfer b14 f14
xfer b13 f13
xfer b12 f12
xfer b11 f11
xfer b10 f10
xfer b9 f9
xfer b8 f8
xfer b7 f7
xfer b6 f6
xfer b5 f5
xfer b4 f4
xfer b3 f3
xfer b2 f2
xfer b1 f1
xfer b0 f0
knit - f30 1
knit - f29 1
knit - f28 1
knit - f27 1
knit - f26 1
knit - f25 1
knit - f24 1
knit - f23 1
knit - f22 1
knit - f21 1
knit - f20 1
knit - f19 1
knit - f18 1
knit - f17 1
knit - f16 1
knit - f15 1
knit - f14 1
knit - f13 1
knit - f12 1
knit - f11 1
knit - f10 1
knit - f9 1
knit - f8 1
knit - f7 1
knit - f6 1
knit - f5 1
knit - f4 1
knit - f3 1
knit - f2 1
knit - f1 1
knit - f0 1
knit + f0 1
knit + f1 1
knit + f2 1
knit + f3 1
knit + f4 1
knit + f5 1
knit + f6 1
knit + f7 1
knit + f8 1
knit + f9 1
knit + f10 1
knit + f11 1
knit + f12 1
knit + f13 1
knit + f14 1
knit + f15 1
knit + f16 1
knit + f17 1
knit + f18 1
knit + f19 1
knit + f20 1
knit + f21 1
knit + f22 1
knit + f23 1
knit + f24 1
knit + f25 1
knit + f26 1
knit + f27 1
knit + f28 1
knit + f29 1
knit + f30 1
xfer f29 b29
xfer f28 b28
xfer f27 b27
xfer f26 b26
xfer f25 b25
xfer f24 b24
xfer f23 b23
xfer f22 b22
xfer f21 b21
xfer f20 b20
xfer f19 b19
xfer f18 b18
xfer f17 b17
xfer f16 b16
xfer f15 b15
xfer f14 b14
xfer f13 b13
xfer f12 b12
xfer f11 b11
xfer f10 b10
xfer f9 b9
xfer f8 b8
xfer f7 b7
xfer f6 b6
xfer f5 b5
xfer f4 b4
xfer f3 b3
xfer f2 b2
xfer f1 b1
knit - f30 1
knit - b29 1
knit - b28 1
knit - b27 1
knit - b26 1
knit - b25 1
knit - b24 1
knit - b23 1
knit - b22 1
knit - b21 1
knit - b20 1
knit - b19 1
knit - b18 1
knit - b17 1
knit - b16 1
knit - b15 1
knit - b14 1
knit - b13 1
knit - b12 1
knit - b11 1
knit - b10 1
knit - b9 1
knit - b8 1
knit - b7 1
knit - b6 1
knit - b5 1
knit - b4 1
knit - b3 1
knit - b2 1
knit - b1 1
knit - f0 1
knit + f0 1
knit + b1 1
knit + b2 1
knit + b3 1
knit + b4 1
knit + b5 1
knit + b6 1
knit + b7 1
knit + b8 1
knit + b9 1
knit + b10 1
knit + b11 1
knit + b12 1
knit + b13 1
knit + b14 1
knit + b15 1
knit + b16 1
knit + b17 1
knit + b18 1
knit + b19 1
knit + b20 1
knit + b21 1
knit + b22 1
knit + b23 1
knit + b24 1
knit + b25 1
knit + b26 1
knit + b27 1
knit + b28 1
knit + b29 1
knit + f30 1
;end 3x3 garter
;begin seed (fb)
knit - f30 1
knit - b29 1
knit - f28 1
knit - b27 1
knit - f26 1
knit - b25 1
knit - f24 1
knit - b23 1
knit - f22 1
knit - b21 1
knit - f20 1
knit - b19 1
knit - f18 1
knit - b17 1
knit - f16 1
knit - b15 1
knit - f14 1
knit - b13 1
knit - f12 1
knit - b11 1
knit - f10 1
knit - b9 1
knit - f8 1
knit - b7 1
knit - f6 1
knit - b5 1
knit - f4 1
knit - b3 1
knit - f2 1
knit - b1 1
knit - f0 1
xfer b29 f29
xfer f28 b28
xfer b27 f27
xfer f26 b26
xfer b25 f25
xfer f24 b24
xfer b23 f23
xfer f22 b22
xfer b21 f21
xfer f20 b20
xfer b19 f19
xfer f18 b18
xfer b17 f17
xfer f16 b16
xfer b15 f15
xfer f14 b14
xfer b13 f13
xfer f12 b12
xfer b11 f11
xfer f10 b10
xfer b9 f9
xfer f8 b8
xfer b7 f7
xfer f6 b6
xfer b5 f5
xfer f4 b4
xfer b3 f3
xfer f2 b2
xfer b1 f1
knit + f0 1
knit + f1 1
knit + b2 1
knit + f3 1
knit + b4 1
knit + f5 1
knit + b6 1
knit + f7 1
knit + b8 1
knit + f9 1
knit + b10 1
knit + f11 1
knit + b12 1
knit + f13 1
knit + b14 1
knit + f15 1
knit + b16 1
knit + f17 1
knit + b18 1
knit + f19 1
knit + b20 1
knit + f21 1
knit + b22 1
knit + f23 1
knit + b24 1
knit + f25 1
knit + b26 1
knit + f27 1
knit + b28 1
knit + f29 1
knit + f30 1
xfer f1 b1
xfer b2 f2
xfer f3 b3
xfer b4 f4
xfer f5 b5
xfer b6 f6
xfer f7 b7
xfer b8 f8
xfer f9 b9
xfer b10 f10
xfer f11 b11
xfer b12 f12
xfer f13 b13
xfer b14 f14
xfer f15 b15
xfer b16 f16
xfer f17 b17
xfer b18 f18
xfer f19 b19
xfer b20 f20
xfer f21 b21
xfer b22 f22
xfer f23 b23
xfer b24 f24
xfer f25 b25
xfer b26 f26
xfer f27 b27
xfer b28 f28
xfer f29 b29
knit - f30 1
knit - b29 1
knit - f28 1
knit - b27 1
knit - f26 1
knit - b25 1
knit - f24 1
knit - b23 1
knit - f22 1
knit - b21 1
knit - f20 1
knit - b19 1
knit - f18 1
knit - b17 1
knit - f16 1
knit - b15 1
knit - f14 1
knit - b13 1
knit - f12 1
knit - b11 1
knit - f10 1
knit - b9 1
knit - f8 1
knit - b7 1
knit - f6 1
knit - b5 1
knit - f4 1
knit - b3 1
knit - f2 1
knit - b1 1
knit - f0 1
xfer b29 f29
xfer f28 b28
xfer b27 f27
xfer f26 b26
xfer b25 f25
xfer f24 b24
xfer b23 f23
xfer f22 b22
xfer b21 f21
xfer f20 b20
xfer b19 f19
xfer f18 b18
xfer b17 f17
xfer f16 b16
xfer b15 f15
xfer f14 b14
xfer b13 f13
xfer f12 b12
xfer b11 f11
xfer f10 b10
xfer b9 f9
xfer f8 b8
xfer b7 f7
xfer f6 b6
xfer b5 f5
xfer f4 b4
xfer b3 f3
xfer f2 b2
xfer b1 f1
knit + f0 1
knit + f1 1
knit + b2 1
knit + f3 1
knit + b4 1
knit + f5 1
knit + b6 1
knit + f7 1
knit + b8 1
knit + f9 1
knit + b10 1
knit + f11 1
knit + b12 1
knit + f13 1
knit + b14 1
knit + f15 1
knit + b16 1
knit + f17 1
knit + b18 1
knit + f19 1
knit + b20 1
knit + f21 1
knit + b22 1
knit + f23 1
knit + b24 1
knit + f25 1
knit + b26 1
knit + f27 1
knit + b28 1
knit + f29 1
knit + f30 1
xfer f1 b1
xfer b2 f2
xfer f3 b3
xfer b4 f4
xfer f5 b5
xfer b6 f6
xfer f7 b7
xfer b8 f8
xfer f9 b9
xfer b10 f10
xfer f11 b11
xfer b12 f12
xfer f13 b13
xfer b14 f14
xfer f15 b15
xfer b16 f16
xfer f17 b17
xfer b18 f18
xfer f19 b19
xfer b20 f20
xfer f21 b21
xfer b22 f22
xfer f23 b23
xfer b24 f24
xfer f25 b25
xfer b26 f26
xfer f27 b27
xfer b28 f28
xfer f29 b29
knit - f30 1
knit - b29 1
knit - f28 1
knit - b27 1
knit - f26 1
knit - b25 1
knit - f24 1
knit - b23 1
knit - f22 1
knit - b21 1
knit - f20 1
knit - b19 1
knit - f18 1
knit - b17 1
knit - f16 1
knit - b15 1
knit - f14 1
knit - b13 1
knit - f12 1
knit - b11 1
knit - f10 1
knit - b9 1
knit - f8 1
knit - b7 1
knit - f6 1
knit - b5 1
knit - f4 1
knit - b3 1
knit - f2 1
knit - b1 1
knit - f0 1
xfer b29 f29
xfer f28 b28
xfer b27 f27
xfer f26 b26
xfer b25 f25
xfer f24 b24
xfer b23 f23
xfer f22 b22
xfer b21 f21
xfer f20 b20
xfer b19 f19
xfer f18 b18
xfer b17 f17
xfer f16 b16
xfer b15 f15
xfer f14 b14
xfer b13 f13
xfer f12 b12
xfer b11 f11
xfer f10 b10
xfer b9 f9
xfer f8 b8
xfer b7 f7
xfer f6 b6
xfer b5 f5
xfer f4 b4
xfer b3 f3
xfer f2 b2
xfer b1 f1
knit + f0 1
knit + f1 1
knit + b2 1
knit + f3 1
knit + b4 1
knit + f5 1
knit + b6 1
knit + f7 1
knit + b8 1
knit + f9 1
knit + b10 1
knit + f11 1
knit + b12 1
knit + f13 1
knit + b14 1
knit + f15 1
knit + b16 1
knit + f17 1
knit + b18 1
knit + f19 1
knit + b20 1
knit + f21 1
knit + b22 1
knit + f23 1
knit + b24 1
knit + f25 1
knit + b26 1
knit + f27 1
knit + b28 1
knit + f29 1
knit + f30 1
xfer f1 b1
xfer b2 f2
xfer f3 b3
xfer b4 f4
xfer f5 b5
xfer b6 f6
xfer f7 b7
xfer b8 f8
xfer f9 b9
xfer b10 f10
xfer f11 b11
xfer b12 f12
xfer f13 b13
xfer b14 f14
xfer f15 b15
xfer b16 f16
xfer f17 b17
xfer b18 f18
xfer f19 b19
xfer b20 f20
xfer f21 b21
xfer b22 f22
xfer f23 b23
xfer b24 f24
xfer f25 b25
xfer b26 f26
xfer f27 b27
xfer b28 f28
xfer f29 b29
knit - f30 1
knit - b29 1
knit - f28 1
knit - b27 1
knit - f26 1
knit - b25 1
knit - f24 1
knit - b23 1
knit - f22 1
knit - b21 1
knit - f20 1
knit - b19 1
knit - f18 1
knit - b17 1
knit - f16 1
knit - b15 1
knit - f14 1
knit - b13 1
knit - f12 1
knit - b11 1
knit - f10 1
knit - b9 1
knit - f8 1
knit - b7 1
knit - f6 1
knit - b5 1
knit - f4 1
knit - b3 1
knit - f2 1
knit - b1 1
knit - f0 1
xfer b29 f29
xfer f28 b28
xfer b27 f27
xfer f26 b26
xfer b25 f25
xfer f24 b24
xfer b23 f23
xfer f22 b22
xfer b21 f21
xfer f20 b20
xfer b19 f19
xfer f18 b18
xfer b17 f17
xfer f16 b16
xfer b15 f15
xfer f14 b14
xfer b13 f13
xfer f12 b12
xfer b11 f11
xfer f10 b10
xfer b9 f9
xfer f8 b8
xfer b7 f7
xfer f6 b6
xfer b5 f5
xfer f4 b4
xfer b3 f3
xfer f2 b2
xfer b1 f1
knit + f0 1
knit + f1 1
knit + b2 1
knit + f3 1
knit + b4 1
knit + f5 1
knit + b6 1
knit + f7 1
knit + b8 1
knit + f9 1
knit + b10 1
knit + f11 1
knit + b12 1
knit + f13 1
knit + b14 1
knit + f15 1
knit + b16 1
knit + f17 1
knit + b18 1
knit + f19 1
knit + b20 1
knit + f21 1
knit + b22 1
knit + f23 1
knit + b24 1
knit + f25 1
knit + b26 1
knit + f27 1
knit + b28 1
knit + f29 1
knit + f30 1
xfer f1 b1
xfer b2 f2
xfer f3 b3
xfer b4 f4
xfer f5 b5
xfer b6 f6
xfer f7 b7
xfer b8 f8
xfer f9 b9
xfer b10 f10
xfer f11 b11
xfer b12 f12
xfer f13 b13
xfer b14 f14
xfer f15 b15
xfer b16 f16
xfer f17 b17
xfer b18 f18
xfer f19 b19
xfer b20 f20
xfer f21 b21
xfer b22 f22
xfer f23 b23
xfer b24 f24
xfer f25 b25
xfer b26 f26
xfer f27 b27
xfer b28 f28
xfer f29 b29
knit - f30 1
knit - b29 1
knit - f28 1
knit - b27 1
knit - f26 1
knit - b25 1
knit - f24 1
knit - b23 1
knit - f22 1
knit - b21 1
knit - f20 1
knit - b19 1
knit - f18 1
knit - b17 1
knit - f16 1
knit - b15 1
knit - f14 1
knit - b13 1
knit - f12 1
knit - b11 1
knit - f10 1
knit - b9 1
knit - f8 1
knit - b7 1
knit - f6 1
knit - b5 1
knit - f4 1
knit - b3 1
knit - f2 1
knit - b1 1
knit - f0 1
xfer b29 f29
xfer f28 b28
xfer b27 f27
xfer f26 b26
xfer b25 f25
xfer f24 b24
xfer b23 f23
xfer f22 b22
xfer b21 f21
xfer f20 b20
xfer b19 f19
xfer f18 b18
xfer b17 f17
xfer f16 b16
xfer b15 f15
xfer f14 b14
xfer b13 f13
xfer f12 b12
xfer b11 f11
xfer f10 b10
xfer b9 f9
xfer f8 b8
xfer b7 f7
xfer f6 b6
xfer b5 f5
xfer f4 b4
xfer b3 f3
xfer f2 b2
xfer b1 f1
knit + f0 1
knit + f1 1
knit + b2 1
knit + f3 1
knit + b4 1
knit + f5 1
knit + b6 1
knit + f7 1
knit + b8 1
knit + f9 1
knit + b10 1
knit + f11 1
knit + b12 1
knit + f13 1
knit + b14 1
knit + f15 1
knit + b16 1
knit + f17 1
knit + b18 1
knit + f19 1
knit + b20 1
knit + f21 1
knit + b22 1
knit + f23 1
knit + b24 1
knit + f25 1
knit + b26 1
knit + f27 1
knit + b28 1
knit + f29 1
knit + f30 1
xfer f1 b1
xfer b2 f2
xfer f3 b3
xfer b4 f4
xfer f5 b5
xfer b6 f6
xfer f7 b7
xfer b8 f8
xfer f9 b9
xfer b10 f10
xfer f11 b11
xfer b12 f12
xfer f13 b13
xfer b14 f14
xfer f15 b15
xfer b16 f16
xfer f17 b17
xfer b18 f18
xfer f19 b19
xfer b20 f20
xfer f21 b21
xfer b22 f22
xfer f23 b23
xfer b24 f24
xfer f25 b25
xfer b26 f26
xfer f27 b27
xfer b28 f28
xfer f29 b29
knit - f30 1
knit - b29 1
knit - f28 1
knit - b27 1
knit - f26 1
knit - b25 1
knit - f24 1
knit - b23 1
knit - f22 1
knit - b21 1
knit - f20 1
knit - b19 1
knit - f18 1
knit - b17 1
knit - f16 1
knit - b15 1
knit - f14 1
knit - b13 1
knit - f12 1
knit - b11 1
knit - f10 1
knit - b9 1
knit - f8 1
knit - b7 1
knit - f6 1
knit - b5 1
knit - f4 1
knit - b3 1
knit - f2 1
knit - b1 1
knit - f0 1
xfer b29 f29
xfer f28 b28
xfer b27 f27
xfer f26 b26
xfer b25 f25
xfer f24 b24
xfer b23 f23
xfer f22 b22
xfer b21 f21
xfer f20 b20
xfer b19 f19
xfer f18 b18
xfer b17 f17
xfer f16 b16
xfer b15 f15
xfer f14 b14
xfer b13 f13
xfer f12 b12
xfer b11 f11
xfer f10 b10
xfer b9 f9
xfer f8 b8
xfer b7 f7
xfer f6 b6
xfer b5 f5
xfer f4 b4
xfer b3 f3
xfer f2 b2
xfer b1 f1
knit + f0 1
knit + f1 1
knit + b2 1
knit + f3 1
knit + b4 1
knit + f5 1
knit + b6 1
knit + f7 1
knit + b8 1
knit + f9 1
knit + b10 1
knit + f11 1
knit + b12 1
knit + f13 1
knit + b14 1
knit + f15 1
knit + b16 1
knit + f17 1
knit + b18 1
knit + f19 1
knit + b20 1
knit + f21 1
knit + b22 1
knit + f23 1
knit + b24 1
knit + f25 1
knit + b26 1
knit + f27 1
knit + b28 1
knit + f29 1
knit + f30 1
xfer f1 b1
xfer b2 f2
xfer f3 b3
xfer b4 f4
xfer f5 b5
xfer b6 f6
xfer f7 b7
xfer b8 f8
xfer f9 b9
xfer b10 f10
xfer f11 b11
xfer b12 f12
xfer f13 b13
xfer b14 f14
xfer f15 b15
xfer b16 f16
xfer f17 b17
xfer b18 f18
xfer f19 b19
xfer b20 f20
xfer f21 b21
xfer b22 f22
xfer f23 b23
xfer b24 f24
xfer f25 b25
xfer b26 f26
xfer f27 b27
xfer b28 f28
xfer f29 b29
knit - f30 1
knit - b29 1
knit - f28 1
knit - b27 1
knit - f26 1
knit - b25 1
knit - f24 1
knit - b23 1
knit - f22 1
knit - b21 1
knit - f20 1
knit - b19 1
knit - f18 1
knit - b17 1
knit - f16 1
knit - b15 1
knit - f14 1
knit - b13 1
knit - f12 1
knit - b11 1
knit - f10 1
knit - b9 1
knit - f8 1
knit - b7 1
knit - f6 1
knit - b5 1
knit - f4 1
knit - b3 1
knit - f2 1
knit - b1 1
knit - f0 1
xfer b29 f29
xfer f28 b28
xfer b27 f27
xfer f26 b26
xfer b25 f25
xfer f24 b24
xfer b23 f23
xfer f22 b22
xfer b21 f21
xfer f20 b20
xfer b19 f19
xfer f18 b18
xfer b17 f17
xfer f16 b16
xfer b15 f15
xfer f14 b14
xfer b13 f13
xfer f12 b12
xfer b11 f11
xfer f10 b10
xfer b9 f9
xfer f8 b8
xfer b7 f7
xfer f6 b6
xfer b5 f5
xfer f4 b4
xfer b3 f3
xfer f2 b2
xfer b1 f1
knit + f0 1
knit + f1 1
knit + b2 1
knit + f3 1
knit + b4 1
knit + f5 1
knit + b6 1
knit + f7 1
knit + b8 1
knit + f9 1
knit + b10 1
knit + f11 1
knit + b12 1
knit + f13 1
knit + b14 1
knit + f15 1
knit + b16 1
knit + f17 1
knit + b18 1
knit + f19 1
knit + b20 1
knit + f21 1
knit + b22 1
knit + f23 1
knit + b24 1
knit + f25 1
knit + b26 1
knit + f27 1
knit + b28 1
knit + f29 1
knit + f30 1
xfer f1 b1
xfer b2 f2
xfer f3 b3
xfer b4 f4
xfer f5 b5
xfer b6 f6
xfer f7 b7
xfer b8 f8
xfer f9 b9
xfer b10 f10
xfer f11 b11
xfer b12 f12
xfer f13 b13
xfer b14 f14
xfer f15 b15
xfer b16 f16
xfer f17 b17
xfer b18 f18
xfer f19 b19
xfer b20 f20
xfer f21 b21
xfer b22 f22
xfer f23 b23
xfer b24 f24
xfer f25 b25
xfer b26 f26
xfer f27 b27
xfer b28 f28
xfer f29 b29
knit - f30 1
knit - b29 1
knit - f28 1
knit - b27 1
knit - f26 1
knit - b25 1
knit - f24 1
knit - b23 1
knit - f22 1
knit - b21 1
knit - f20 1
knit - b19 1
knit - f18 1
knit - b17 1
knit - f16 1
knit - b15 1
knit - f14 1
knit - b13 1
knit - f12 1
knit - b11 1
knit - f10 1
knit - b9 1
knit - f8 1
knit - b7 1
knit - f6 1
knit - b5 1
knit - f4 1
knit - b3 1
knit - f2 1
knit - b1 1
knit - f0 1
xfer b29 f29
xfer f28 b28
xfer b27 f27
xfer f26 b26
xfer b25 f25
xfer f24 b24
xfer b23 f23
xfer f22 b22
xfer b21 f21
xfer f20 b20
xfer b19 f19
xfer f18 b18
xfer b17 f17
xfer f16 b16
xfer b15 f15
xfer f14 b14
xfer b13 f13
xfer f12 b12
xfer b11 f11
xfer f10 b10
xfer b9 f9
xfer f8 b8
xfer b7 f7
xfer f6 b6
xfer b5 f5
xfer f4 b4
xfer b3 f3
xfer f2 b2
xfer b1 f1
knit + f0 1
knit + f1 1
knit + b2 1
knit + f3 1
knit + b4 1
knit + f5 1
knit + b6 1
knit + f7 1
knit + b8 1
knit + f9 1
knit + b10 1
knit + f11 1
knit + b12 1
knit + f13 1
knit + b14 1
knit + f15 1
knit + b16 1
knit + f17 1
knit + b18 1
knit + f19 1
knit + b20 1
knit + f21 1
knit + b22 1
knit + f23 1
knit + b24 1
knit + f25 1
knit + b26 1
knit + f27 1
knit + b28 1
knit + f29 1
knit + f30 1
xfer f1 b1
xfer b2 f2
xfer f3 b3
xfer b4 f4
xfer f5 b5
xfer b6 f6
xfer f7 b7
xfer b8 f8
xfer f9 b9
xfer b10 f10
xfer f11 b11
xfer b12 f12
xfer f13 b13
xfer b14 f14
xfer f15 b15
xfer b16 f16
xfer f17 b17
xfer b18 f18
xfer f19 b19
xfer b20 f20
xfer f21 b21
xfer b22 f22
xfer f23 b23
xfer b24 f24
xfer f25 b25
xfer b26 f26
xfer f27 b27
xfer b28 f28
xfer f29 b29
knit - f30 1
knit - b29 1
knit - f28 1
knit - b27 1
knit - f26 1
knit - b25 1
knit - f24 1
knit - b23 1
knit - f22 1
knit - b21 1
knit - f20 1
knit - b19 1
knit - f18 1
knit - b17 1
knit - f16 1
knit - b15 1
knit - f14 1
knit - b13 1
knit - f12 1
knit - b11 1
knit - f10 1
knit - b9 1
knit - f8 1
knit - b7 1
knit - f6 1
knit - b5 1
knit - f4 1
knit - b3 1
knit - f2 1
knit - b1 1
knit - f0 1
xfer b29 f29
xfer f28 b28
xfer b27 f27
xfer f26 b26
xfer b25 f25
xfer f24 b24
xfer b23 f23
xfer f22 b22
xfer b21 f21
xfer f20 b20
xfer b19 f19
xfer f18 b18
xfer b17 f17
xfer f16 b16
xfer b15 f15
xfer f14 b14
xfer b13 f13
xfer f12 b12
xfer b11 f11
xfer f10 b10
xfer b9 f9
xfer f8 b8
xfer b7 f7
xfer f6 b6
xfer b5 f5
xfer f4 b4
xfer b3 f3
xfer f2 b2
xfer b1 f1
knit + f0 1
knit + f1 1
knit + b2 1
knit + f3 1
knit + b4 1
knit + f5 1
knit + b6 1
knit + f7 1
knit + b8 1
knit + f9 1
knit + b10 1
knit + f11 1
knit + b12 1
knit + f13 1
knit + b14 1
knit + f15 1
knit + b16 1
knit + f17 1
knit + b18 1
knit + f19 1
knit + b20 1
knit + f21 1
knit + b22 1
knit + f23 1
knit + b24 1
knit + f25 1
knit + b26 1
knit + f27 1
knit + b28 1
knit + f29 1
knit + f30 1
xfer f1 b1
xfer b2 f2
xfer f3 b3
xfer b4 f4
xfer f5 b5
xfer b6 f6
xfer f7 b7
xfer b8 f8
xfer f9 b9
xfer b10 f10
xfer f11 b11
xfer b12 f12
xfer f13 b13
xfer b14 f14
xfer f15 b15
xfer b16 f16
xfer f17 b17
xfer b18 f18
xfer f19 b19
xfer b20 f20
xfer f21 b21
xfer b22 f22
xfer f23 b23
xfer b24 f24
xfer f25 b25
xfer b26 f26
xfer f27 b27
xfer b28 f28
xfer f29 b29
knit - f30 1
knit - b29 1
knit - f28 1
knit - b27 1
knit - f26 1
knit - b25 1
knit - f24 1
knit - b23 1
knit - f22 1
knit - b21 1
knit - f20 1
knit - b19 1
knit - f18 1
knit - b17 1
knit - f16 1
knit - b15 1
knit - f14 1
knit - b13 1
knit - f12 1
knit - b11 1
knit - f10 1
knit - b9 1
knit - f8 1
knit - b7 1
knit - f6 1
knit - b5 1
knit - f4 1
knit - b3 1
knit - f2 1
knit - b1 1
knit - f0 1
xfer b29 f29
xfer f28 b28
xfer b27 f27
xfer f26 b26
xfer b25 f25
xfer f24 b24
xfer b23 f23
xfer f22 b22
xfer b21 f21
xfer f20 b20
xfer b19 f19
xfer f18 b18
xfer b17 f17
xfer f16 b16
xfer b15 f15
xfer f14 b14
xfer b13 f13
xfer f12 b12
xfer b11 f11
xfer f10 b10
xfer b9 f9
xfer f8 b8
xfer b7 f7
xfer f6 b6
xfer b5 f5
xfer f4 b4
xfer b3 f3
xfer f2 b2
xfer b1 f1
knit + f0 1
knit + f1 1
knit + b2 1
knit + f3 1
knit + b4 1
knit + f5 1
knit + b6 1
knit + f7 1
knit + b8 1
knit + f9 1
knit + b10 1
knit + f11 1
knit + b12 1
knit + f13 1
knit + b14 1
knit + f15 1
knit + b16 1
knit + f17 1
knit + b18 1
knit + f19 1
knit + b20 1
knit + f21 1
knit + b22 1
knit + f23 1
knit + b24 1
knit + f25 1
knit + b26 1
knit + f27 1
knit + b28 1
knit + f29 1
knit + f30 1
xfer f1 b1
xfer b2 f2
xfer f3 b3
xfer b4 f4
xfer f5 b5
xfer b6 f6
xfer f7 b7
xfer b8 f8
xfer f9 b9
xfer b10 f10
xfer f11 b11
xfer b12 f12
xfer f13 b13
xfer b14 f14
xfer f15 b15
xfer b16 f16
xfer f17 b17
xfer b18 f18
xfer f19 b19
xfer b20 f20
xfer f21 b21
xfer b22 f22
xfer f23 b23
xfer b24 f24
xfer f25 b25
xfer b26 f26
xfer f27 b27
xfer b28 f28
xfer f29 b29
knit - f30 1
knit - b29 1
knit - f28 1
knit - b27 1
knit - f26 1
knit - b25 1
knit - f24 1
knit - b23 1
knit - f22 1
knit - b21 1
knit - f20 1
knit - b19 1
knit - f18 1
knit - b17 1
knit - f16 1
knit - b15 1
knit - f14 1
knit - b13 1
knit - f12 1
knit - b11 1
knit - f10 1
knit - b9 1
knit - f8 1
knit - b7 1
knit - f6 1
knit - b5 1
knit - f4 1
knit - b3 1
knit - f2 1
knit - b1 1
knit - f0 1
xfer b29 f29
xfer f28 b28
xfer b27 f27
xfer f26 b26
xfer b25 f25
xfer f24 b24
xfer b23 f23
xfer f22 b22
xfer b21 f21
xfer f20 b20
xfer b19 f19
xfer f18 b18
xfer b17 f17
xfer f16 b16
xfer b15 f15
xfer f14 b14
xfer b13 f13
xfer f12 b12
xfer b11 f11
xfer f10 b10
xfer b9 f9
xfer f8 b8
xfer b7 f7
xfer f6 b6
xfer b5 f5
xfer f4 b4
xfer b3 f3
xfer f2 b2
xfer b1 f1
knit + f0 1
knit + f1 1
knit + b2 1
knit + f3 1
knit + b4 1
knit + f5 1
knit + b6 1
knit + f7 1
knit + b8 1
knit + f9 1
knit + b10 1
knit + f11 1
knit + b12 1
knit + f13 1
knit + b14 1
knit + f15 1
knit + b16 1
knit + f17 1
knit + b18 1
knit + f19 1
knit + b20 1
knit + f21 1
knit + b22 1
knit + f23 1
knit + b24 1
knit + f25 1
knit + b26 1
knit + f27 1
knit + b28 1
knit + f29 1
knit + f30 1
xfer f1 b1
xfer b2 f2
xfer f3 b3
xfer b4 f4
xfer f5 b5
xfer b6 f6
xfer f7 b7
xfer b8 f8
xfer f9 b9
xfer b10 f10
xfer f11 b11
xfer b12 f12
xfer f13 b13
xfer b14 f14
xfer f15 b15
xfer b16 f16
xfer f17 b17
xfer b18 f18
xfer f19 b19
xfer b20 f20
xfer f21 b21
xfer b22 f22
xfer f23 b23
xfer b24 f24
xfer f25 b25
xfer b26 f26
xfer f27 b27
xfer b28 f28
xfer f29 b29
knit - f30 1
knit - b29 1
knit - f28 1
knit - b27 1
knit - f26 1
knit - b25 1
knit - f24 1
knit - b23 1
knit - f22 1
knit - b21 1
knit - f20 1
knit - b19 1
knit - f18 1
knit - b17 1
knit - f16 1
knit - b15 1
knit - f14 1
knit - b13 1
knit - f12 1
knit - b11 1
knit - f10 1
knit - b9 1
knit - f8 1
knit - b7 1
knit - f6 1
knit - b5 1
knit - f4 1
knit - b3 1
knit - f2 1
knit - b1 1
knit - f0 1
xfer b29 f29
xfer f28 b28
xfer b27 f27
xfer f26 b26
xfer b25 f25
xfer f24 b24
xfer b23 f23
xfer f22 b22
xfer b21 f21
xfer f20 b20
xfer b19 f19
xfer f18 b18
xfer b17 f17
xfer f16 b16
xfer b15 f15
xfer f14 b14
xfer b13 f13
xfer f12 b12
xfer b11 f11
xfer f10 b10
xfer b9 f9
xfer f8 b8
xfer b7 f7
xfer f6 b6
xfer b5 f5
xfer f4 b4
xfer b3 f3
xfer f2 b2
xfer b1 f1
knit + f0 1
knit + f1 1
knit + b2 1
knit + f3 1
knit + b4 1
knit + f5 1
knit + b6 1
knit + f7 1
knit + b8 1
knit + f9 1
knit + b10 1
knit + f11 1
knit + b12 1
knit + f13 1
knit + b14 1
knit + f15 1
knit + b16 1
knit + f17 1
knit + b18 1
knit + f19 1
knit + b20 1
knit + f21 1
knit + b22 1
knit + f23 1
knit + b24 1
knit + f25 1
knit + b26 1
knit + f27 1
knit + b28 1
knit + f29 1
knit + f30 1
xfer f1 b1
xfer b2 f2
xfer f3 b3
xfer b4 f4
xfer f5 b5
xfer b6 f6
xfer f7 b7
xfer b8 f8
xfer f9 b9
xfer b10 f10
xfer f11 b11
xfer b12 f12
xfer f13 b13
xfer b14 f14
xfer f15 b15
xfer b16 f16
xfer f17 b17
xfer b18 f18
xfer f19 b19
xfer b20 f20
xfer f21 b21
xfer b22 f22
xfer f23 b23
xfer b24 f24
xfer f25 b25
xfer b26 f26
xfer f27 b27
xfer b28 f28
xfer f29 b29
knit - f30 1
knit - b29 1
knit - f28 1
knit - b27 1
knit - f26 1
knit - b25 1
knit - f24 1
knit - b23 1
knit - f22 1
knit - b21 1
knit - f20 1
knit - b19 1
knit - f18 1
knit - b17 1
knit - f16 1
knit - b15 1
knit - f14 1
knit - b13 1
knit - f12 1
knit - b11 1
knit - f10 1
knit - b9 1
knit - f8 1
knit - b7 1
knit - f6 1
knit - b5 1
knit - f4 1
knit - b3 1
knit - f2 1
knit - b1 1
knit - f0 1
xfer b29 f29
xfer f28 b28
xfer b27 f27
xfer f26 b26
xfer b25 f25
xfer f24 b24
xfer b23 f23
xfer f22 b22
xfer b21 f21
xfer f20 b20
xfer b19 f19
xfer f18 b18
xfer b17 f17
xfer f16 b16
xfer b15 f15
xfer f14 b14
xfer b13 f13
xfer f12 b12
xfer b11 f11
xfer f10 b10
xfer b9 f9
xfer f8 b8
xfer b7 f7
xfer f6 b6
xfer b5 f5
xfer f4 b4
xfer b3 f3
xfer f2 b2
xfer b1 f1
knit + f0 1
knit + f1 1
knit + b2 1
knit + f3 1
knit + b4 1
knit + f5 1
knit + b6 1
knit + f7 1
knit + b8 1
knit + f9 1
knit + b10 1
knit + f11 1
knit + b12 1
knit + f13 1
knit + b14 1
knit + f15 1
knit + b16 1
knit + f17 1
knit + b18 1
knit + f19 1
knit + b20 1
knit + f21 1
knit + b22 1
knit + f23 1
knit + b24 1
knit + f25 1
knit + b26 1
knit + f27 1
knit + b28 1
knit + f29 1
knit + f30 1
xfer f1 b1
xfer b2 f2
xfer f3 b3
xfer b4 f4
xfer f5 b5
xfer b6 f6
xfer f7 b7
xfer b8 f8
xfer f9 b9
xfer b10 f10
xfer f11 b11
xfer b12 f12
xfer f13 b13
xfer b14 f14
xfer f15 b15
xfer b16 f16
xfer f17 b17
xfer b18 f18
xfer f19 b19
xfer b20 f20
xfer f21 b21
xfer b22 f22
xfer f23 b23
xfer b24 f24
xfer f25 b25
xfer b26 f26
xfer f27 b27
xfer b28 f28
xfer f29 b29
knit - f30 1
knit - b29 1
knit - f28 1
knit - b27 1
knit - f26 1
knit - b25 1
knit - f24 1
knit - b23 1
knit - f22 1
knit - b21 1
knit - f20 1
knit - b19 1
knit - f18 1
knit - b17 1
knit - f16 1
knit - b15 1
knit - f14 1
knit - b13 1
knit - f12 1
knit - b11 1
knit - f10 1
knit - b9 1
knit - f8 1
knit - b7 1
knit - f6 1
knit - b5 1
knit - f4 1
knit - b3 1
knit - f2 1
knit - b1 1
knit - f0 1
xfer b29 f29
xfer f28 b28
xfer b27 f27
xfer f26 b26
xfer b25 f25
xfer f24 b24
xfer b23 f23
xfer f22 b22
xfer b21 f21
xfer f20 b20
xfer b19 f19
xfer f18 b18
xfer b17 f17
xfer f16 b16
xfer b15 f15
xfer f14 b14
xfer b13 f13
xfer f12 b12
xfer b11 f11
xfer f10 b10
xfer b9 f9
xfer f8 b8
xfer b7 f7
xfer f6 b6
xfer b5 f5
xfer f4 b4
xfer b3 f3
xfer f2 b2
xfer b1 f1
knit + f0 1
knit + f1 1
knit + b2 1
knit + f3 1
knit + b4 1
knit + f5 1
knit + b6 1
knit + f7 1
knit + b8 1
knit + f9 1
knit + b10 1
knit + f11 1
knit + b12 1
knit + f13 1
knit + b14 1
knit + f15 1
knit + b16 1
knit + f17 1
knit + b18 1
knit + f19 1
knit + b20 1
knit + f21 1
knit + b22 1
knit + f23 1
knit + b24 1
knit + f25 1
knit + b26 1
knit + f27 1
knit + b28 1
knit + f29 1
knit + f30 1
xfer f1 b1
xfer b2 f2
xfer f3 b3
xfer b4 f4
xfer f5 b5
xfer b6 f6
xfer f7 b7
xfer b8 f8
xfer f9 b9
xfer b10 f10
xfer f11 b11
xfer b12 f12
xfer f13 b13
xfer b14 f14
xfer f15 b15
xfer b16 f16
xfer f17 b17
xfer b18 f18
xfer f19 b19
xfer b20 f20
xfer f21 b21
xfer b22 f22
xfer f23 b23
xfer b24 f24
xfer f25 b25
xfer b26 f26
xfer f27 b27
xfer b28 f28
xfer f29 b29
knit - f30 1
knit - b29 1
knit - f28 1
knit - b27 1
knit - f26 1
knit - b25 1
knit - f24 1
knit - b23 1
knit - f22 1
knit - b21 1
knit - f20 1
knit - b19 1
knit - f18 1
knit - b17 1
knit - f16 1
knit - b15 1
knit - f14 1
knit - b13 1
knit - f12 1
knit - b11 1
knit - f10 1
knit - b9 1
knit - f8 1
knit - b7 1
knit - f6 1
knit - b5 1
knit - f4 1
knit - b3 1
knit - f2 1
knit - b1 1
knit - f0 1
xfer b29 f29
xfer f28 b28
xfer b27 f27
xfer f26 b26
xfer b25 f25
xfer f24 b24
xfer b23 f23
xfer f22 b22
xfer b21 f21
xfer f20 b20
xfer b19 f19
xfer f18 b18
xfer b17 f17
xfer f16 b16
xfer b15 f15
xfer f14 b14
xfer b13 f13
xfer f12 b12
xfer b11 f11
xfer f10 b10
xfer b9 f9
xfer f8 b8
xfer b7 f7
xfer f6 b6
xfer b5 f5
xfer f4 b4
xfer b3 f3
xfer f2 b2
xfer b1 f1
knit + f0 1
knit + f1 1
knit + b2 1
knit + f3 1
knit + b4 1
knit + f5 1
knit + b6 1
knit + f7 1
knit + b8 1
knit + f9 1
knit + b10 1
knit + f11 1
knit + b12 1
knit + f13 1
knit + b14 1
knit + f15 1
knit + b16 1
knit + f17 1
knit + b18 1
knit + f19 1
knit + b20 1
knit + f21 1
knit + b22 1
knit + f23 1
knit + b24 1
knit + f25 1
knit + b26 1
knit + f27 1
knit + b28 1
knit + f29 1
knit + f30 1
;end seed (fb)
;begin drop finish
outhook 1
drop f0
drop f1
drop f2
drop f3
drop f4
drop f5
drop f6
drop f7
drop f8
drop f9
drop f10
drop f11
drop f12
drop f13
drop f14
drop f15
drop f16
drop f17
drop f18
drop f19
drop f20
drop f21
drop f22
drop f23
drop f24
drop f25
drop f26
drop f27
drop f28
drop f29
drop f30
;end drop finish
